---
title: "Percentage_May22"
author: "Carrie Wright"
date: "May 25, 2018"
output: html_document
---
```{r, echo = TRUE, eval=TRUE}
library(dplyr)
get_test_names <- function(data){
  test_names <<- data.frame(combn(unique(names(data)), m= 2))
}

get_test_results<- function(data,test_names) {
  tresults<<-list()
  tested_names1<<-list()
  tested_names2<<-list()
  for(i in names(test_names)){
    #tested_names[[i]]<<-(test_names[i][,1])
    Kit1<-data[grep(test_names[i][1,], names(data))]
    Kit2<-data[grep(test_names[i][2,], names(data))]
    #Kit1<-data.frame(select(data, names(data)[names(data) %in% test_names[i][1,]]))
    #Kit2<-data.frame(select(data, names(data)[names(data) %in% test_names[i][2,]]))
    tested_names1[[i]]<<-names(Kit1)
    tested_names2[[i]]<<-names(Kit2)
    # colnames(Kit1)<-c("error")
    # colnames(Kit2)<-c("error")
    tresults[[i]]<<-t.test(x=Kit1[[1]] ,y=Kit2[[1]], paired = FALSE) ### may have messed things up adding paired = TRUE previously had more ))
    tested_kits <<-paste0(tested_names1, "&", tested_names2)
  }
}

get_ttestStats<- function(x) {
  #print(length(test_names))
  c(t =format(x$statistic, digits = 2),
    df = format(x$parameter, digits = 0),
    p.value = format(x$p.value, scientific = TRUE, digits = 2),
    bonferroni_thresh = format(.05/length(test_names), digits = 2),
    sig = ifelse(x$p.value<(.05/length(test_names)), "yes", "no"))
}

#get_lmStats <-function(x) {
#  c(p=x$coefficients[2,4], scientific = TRUE, digits =2)
#}
```

```{r}
library("here")
library("ggplot2")
library("reshape2")
library("jaffelab")
library(RColorBrewer) #set 3 or 1
library(wesanderson)

percentages <- read.table(here("competitive_percentages.csv"), sep = ",", header = TRUE)
colnames(percentages) <-gsub("X.", "", colnames(percentages))
percentages$name<- paste0(percentages$Method, "_", percentages$StaringAmount_of_totalRNA)
percentages<- cbind(percentages$File, percentages$unmapped, percentages[22:length(colnames(percentages))])
colnames(percentages)<- c("File", "unmapped", "miRNA","piRNA", "rRNA", "scaRNA", "snoRNA", "snRNA", "tRNA", "name")
percentages$File= factor(percentages$File,levels(percentages$File)[percentages$File])# reorder levels of files to be the same as in the dataframe
#percents <- cbind(percentages$File, percentages$name, percentages[22:length(colnames(percentages))])
mp <-melt(percentages)
mp$Method <- ss(x = mp$name, "_", 1)
mp$amount <- ss(x = mp$name, "_", 2)
mp$File<-factor(mp$File, ordered = TRUE)
colnames(mp)[5] <-c("Read_type")
mp$Read_type= factor(mp$Read_type,levels = c("unmapped","rRNA","tRNA", "scaRNA", "snoRNA", "snRNA","piRNA","miRNA"))

pdf(file =here("Figures/Raw_plots/stackedbar_percentages.pdf"),width=10,height=8)
ggplot(mp, aes(x = File, y = value, color = Read_type)) +geom_bar(stat  = "identity", position = "stack", aes(y =value, fill = Read_type), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text( size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 15), axis.title.y=element_text(size = 20)) +scale_x_discrete(labels= mp$name)  +ylab("Percentage of reads")   +    scale_fill_manual(values =c("gray", "lightsteelblue4","thistle4",   "maroon2", "olivedrab2", "indianred3", "steelblue2", "orange2"))
 dev.off() 
  scale_fill_manual(values =c("snow2", "snow4","snow3",   "maroon2", "olivedrab2", "indianred3", "steelblue2", "orange2"))

 scale_fill_manual(values =c("gray", "lightsteelblue4","thistle4",   "maroon2", "olivedrab2", "indianred3", "steelblue2", "orange2"))
scale_fill_manual(values =c("gray", "lightsteelblue4","thistle4",   "maroon2", "olivedrab2", "indianred3", "royalblue2", "orange2"))
 scale_fill_manual(values =c("gray", "slateblue1", "seagreen", "salmon3", "yellow2", "indianred3", "blue", "orange2"))
scale_fill_manual(values =c("gray", "slateblue1", "seagreen", "salmon3", "yellow2", "red4", "blue", "orange2"))
  scale_fill_manual(values = rev(brewer.pal(8, "Set2")))
  scale_fill_brewer(rev(palette="Dark2"))

#scale_fill_manual(values = wes_palette(7, "BottleRocket"))
#\+ scale_fill_brewer(palette="Pastel1")



mp1000 <- mp[which(mp$amount == "1000"),]
mp1000$toagg<-paste0(mp1000$Method,"_", mp1000$Read_type)
aggregate_1000 <- aggregate(mp1000$value, by=list(mp1000$toagg), FUN = mean)
aggregate_1000$Method <- ss(aggregate_1000$Group.1, "_", 1)
aggregate_1000$Read_type <- ss(aggregate_1000$Group.1, "_", 2)
aggregate_1000$Read_type <- factor(aggregate_1000$Read_type, levels=(aggregate_1000$Read_type)[c(8,1,3,7,2,5,6,4)])

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

n = 6
cols = gg_color_hue(n)
cols<-cols[1:4]

pdf(file =here("Figures/Raw_plots/percentages_1000ng.pdf"),width=10,height=6)
ggplot(aggregate_1000, aes(x = Read_type, y = x, color = Method)) +geom_bar(stat  = "identity", position = "dodge", aes(y =x, fill = Method), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text( size = 10, angle = 60, face = "bold", colour = "black", hjust = 1), axis.text.y=element_text(size = 15, colour = "black"), axis.title.y=element_text(size = 20), legend.position = "none", strip.text.x = element_text(size = 18)) +ylab("Percentage of reads")+ facet_grid(.~Method)  +scale_fill_manual(values = cols)
dev.off()
pdf(file = here("Figures/Raw_plots/percentages_1000ng.pdf"),width=12,height=5)
ggplot(aggregate_1000, aes(x = Method, y = x, color = Method)) +geom_bar(stat  = "identity", position = "dodge", aes(y =x, fill = Method), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text( size = 15, angle = 60, face = "bold", colour = "black", hjust = 1), axis.text.y=element_text(size = 15, colour = "black"), axis.title.y=element_text(size = 20), legend.position = "none", strip.text.x = element_text(size = 18)) +ylab("Percentage of reads")+ facet_grid(.~Read_type)  +scale_fill_manual(values = cols)
dev.off()
ggplot(aggregate_1000, aes(x = Method, y = x, color = Method)) +geom_bar(stat  = "identity", position = "dodge", aes(y =x, fill = Method), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text( size = 10, angle = 60, face = "bold", colour = "black", hjust = 1), axis.text.y=element_text(size = 15, colour = "black"), axis.title.y=element_text(size = 20), legend.position = "none", strip.text.x = element_text(size = 18)) +ylab("Percentage of reads")+ facet_grid(Read_type~., scales = "free")  +scale_fill_manual(values = cols)

ggplot(mp1000, aes(x = Read_type, y = value, color = Method)) +geom_boxplot(aes(y =value, fill = Method), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text( size = 10, angle = 60, face = "bold", colour = "black", hjust = 1), axis.text.y=element_text(size = 15), axis.title.y=element_text(size = 20), legend.position = "none") +ylab("Percentage of reads")+ facet_grid(~Method)  +scale_fill_manual(values = cols)

#stats
percentages$Method <- ss(percentages$name, "_", 1)
percentages$amount <-ss(percentages$name, "_", 2)
percent_1000 <- percentages[which(percentages$amount == "1000"),]

miRNA <-(aov(percent_1000$miRNA ~ percent_1000$Method)) #same as anova(lm(etc...))
TukeyHSD(miRNA, ordered = FALSE)
anova(lm(percent_1000$miRNA ~ percent_1000$Method))
anova(lm(percent_1000$unmapped ~ percent_1000$Method))
anova(lm(percent_1000$rRNA ~ percent_1000$Method))
anova(lm(percent_1000$tRNA ~ percent_1000$Method))
anova(lm(percent_1000$piRNA ~ percent_1000$Method))
anova(lm(percent_1000$snoRNA ~ percent_1000$Method))
anova(lm(percent_1000$snRNA ~ percent_1000$Method))
anova(lm(percent_1000$scaRNA ~ percent_1000$Method)) # no difference after multiple correction
percent_1000$key <- rep(c(1:4), 4)
percent_1000<-as.data.table(percent_1000)


unmapped<-data.frame(dcast(percent_1000, key~Method, value.var = "unmapped"))
unmapped$key<-NULL
miRNA<-data.frame(dcast(percent_1000, key~Method, value.var = "miRNA"))
miRNA$key<-NULL
rRNA<-data.frame(dcast(percent_1000, key~Method, value.var = "rRNA"))
rRNA$key<-NULL
tRNA<-data.frame(dcast(percent_1000, key~Method, value.var = "tRNA"))
tRNA$key<-NULL
snRNA<-data.frame(dcast(percent_1000, key~Method, value.var = "snRNA"))
snRNA$key<-NULL
snoRNA<-data.frame(dcast(percent_1000, key~Method, value.var = "snoRNA"))
snoRNA$key<-NULL
piRNA<-data.frame(dcast(percent_1000, key~Method, value.var = "piRNA"))
piRNA$key<-NULL

```

```{r}

get_test_names(unmapped)
get_test_results(data = unmapped, test_names = test_names)
ttestStats_across<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats_across)<-tested_kits
ttestStats_across

get_test_names(miRNA)
get_test_results(data = miRNA, test_names = test_names)
ttestStats_across<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats_across)<-tested_kits
ttestStats_across

get_test_names(rRNA)
get_test_results(data = rRNA, test_names = test_names)
ttestStats_across<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats_across)<-tested_kits
ttestStats_across


get_test_names(tRNA)
get_test_results(data = tRNA, test_names = test_names)
ttestStats_across<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats_across)<-tested_kits
ttestStats_across

get_test_names(piRNA)
get_test_results(data = piRNA, test_names = test_names)
ttestStats_across<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats_across)<-tested_kits
ttestStats_across

get_test_names(snoRNA)
get_test_results(data = snoRNA, test_names = test_names)
ttestStats_across<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats_across)<-tested_kits
ttestStats_across

get_test_names(snRNA)
get_test_results(data = snRNA, test_names = test_names)
ttestStats_across<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats_across)<-tested_kits
ttestStats_across

```







#############may want to keep something below from previous analysis?

```{r}
library("here")
library("ggplot2")
library("reshape2")
percentages <- read.table(here("competitive_percentages.csv"), sep = ",", header = TRUE)
colnames(percentages) <-gsub("X.", "", colnames(percentages))
Pheno <-cbind(percentages[1:4], percentages$total_reads)
names_files<-paste0(percentages$Method, "_",percentages$StaringAmount_of_totalRNA)
percents <-cbind(names_files, percentages[22:length(colnames(percentages))])
colnames(percents)<- c("names_files", "miRNA","piRNA", "rRNA", "scaRNA", "snoRNA", "snRNA", "tRNA")


mRNAs<-melt(percents)
mRNAs$names_files<-as.character(mRNAs$names_files)
mRNAs$Method<-ss(mRNAs$names_files, pattern = "_",1)
mRNAs$amount<-ss(mRNAs$names_files, pattern = "_",2)

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

n = 6
cols = gg_color_hue(n)
cols<-cols[1:4]

mRNAs$Method<-factor(mRNAs$Method, levels =c("Clontech","Illumina", "NEB","NEXTflex"))
mRNAs$variable<-factor(mRNAs$variable, levels= c("miRNA","rRNA", "tRNA", "piRNA", "snoRNA", "snRNA", "scaRNA"))

ggplot(mRNAs, aes(x = variable, y = value, color = Method)) +geom_bar(stat  = "identity", position = "dodge", aes(y =value, fill = Method)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(amount~.) +scale_fill_manual(values=cols)+scale_color_manual(values=cols)

ggplot(mRNAs, aes(x = Method, y = value, color = variable)) +geom_bar(stat  = "identity", position = "stack", aes(y =value, fill = Method)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(Method~.) +scale_fill_manual(values=cols)+scale_color_manual(values=cols)

mRNAs$toagg<-paste0(mRNAs$variable,"_", mRNAs$names_files)
aggdata <-aggregate(mRNAs$value, by=list(mRNAs$toagg), FUN=mean)
aggdata$variable<- ss(aggdata$Group.1, "_", 1)
aggdata$Method<- ss(aggdata$Group.1, "_", 2)
aggdata$amount<- ss(aggdata$Group.1, "_", 3)
ggplot(aggdata, aes(x = variable, y = x, color = Method, group = variable)) +geom_bar(stat  = "identity", position = "identity", aes(y =x, fill = Method), col = "black") +theme(axis.title.x=element_blank(), axis.text.x=element_text(size = 14, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 20), axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 20))+facet_grid(amount~Method)+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +ggtitle("Percent of reads mapping to other RNAs") +labs(y="Percent of reads", x ="none")

aggdata$amount<-factor(aggdata$amount, levels= c("100","250", "500", "1000", "1500", "2000"))
aggdata$Method<-factor(aggdata$Method, levels =c("Clontech","Illumina", "NEB","NEXTflex"))
aggdata$variable<-factor(aggdata$variable, levels= c("miRNA","rRNA", "tRNA", "piRNA", "snoRNA", "snRNA", "scaRNA"))

ggplot(aggdata, aes(x = amount, y = x, color = Method, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =x, fill = Method), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), strip.text.x = element_text(size = 15), strip.text.y = element_text(size = 15),legend.position = "NULL")+facet_grid(Method~variable)+scale_fill_manual(values=cols)+scale_color_manual(values=cols)  +labs(y="Percent of reads", x ="none")

ggplot(aggdata, aes(x = amount, y = x, color = Method, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =x, fill = Method), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), strip.text.x = element_text(size = 15), strip.text.y = element_text(size = 15),legend.position = "NULL")+facet_grid(variable~Method)+scale_fill_manual(values=cols)+scale_color_manual(values=cols)  +labs(y="Percent of reads", x ="none")

ggplot(aggdata, aes(x = amount, y = x, color = Method, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =x, fill = Method), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), strip.text.x = element_text(size = 15), strip.text.y = element_text(size = 15),legend.position = "NULL")+facet_grid(variable~Method, scales = "free")+scale_fill_manual(values=cols)+scale_color_manual(values=cols)  +labs(y="Percent of reads", x ="none")


```
Just - miRNA - perhaps we should just use the report for this...
```{r}


miRNA_data <- mRNAs[grep("miRNA", mRNAs$variable),]


data_1000 <- miRNA_data[grep("1000", miRNA_data$Input_Amount),]
anova(lm(data_1000$value ~ data_1000$Kit))
t.test(data_1000$value[grep("NEB", data_1000$Kit)], data_1000$value[grep("NEXTflex", data_1000$Kit)])
t.test(data_1000$value[grep("Illumina", data_1000$Kit)], data_1000$value[grep("NEXTflex", data_1000$Kit)])
t.test(data_1000$value[grep("Illumina", data_1000$Kit)], data_1000$value[grep("NEB", data_1000$Kit)])
t.test(data_1000$value[grep("Illumina", data_1000$Kit)], data_1000$value[grep("Clontech", data_1000$Kit)])
t.test(data_1000$value[grep("NEB", data_1000$Kit)], data_1000$value[grep("Clontech", data_1000$Kit)])
t.test(data_1000$value[grep("NEXTflex", data_1000$Kit)], data_1000$value[grep("Clontech", data_1000$Kit)])


ggplot(data_1000, aes(x = Kit, y = value, color = Kit)) +geom_boxplot(aes(y =value, fill = Kit)) +geom_jitter(col = "black") +theme(legend.position = "none", axis.title.x=element_blank(), axis.text.x=element_text(size = 15, angle = 60,hjust = 1, colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 20))+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +ggtitle("Percent of reads mapping to miRNA") +labs(y="Percent of reads", x ="none")
```
Just other RNAs
```{r}
library(jaffelab)

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

n = 6
cols = gg_color_hue(n)
RNAs <-RNAs[-grep("miRNA", colnames(RNAs))]
RNAs <-RNAs[-grep("hairpin", colnames(RNAs))]
RNAs$type <- paste0(RNAs$Kit, "_",RNAs$Input_Amount)
aggdata <-aggregate(RNAs[,3:11], by=list(RNAs$type), FUN=mean)
aggdata$Kit <-ss(aggdata$Group.1, "_",1)
aggdata$Input_Amount <-ss(aggdata$Group.1, "_",2)
colnames(aggdata)<- c("group", "Mito","rRNA", "snRNA", "CD_box", "HACA_box", "scaRNA", "piRNA", "tRNA", "mRNA","Kit", "Input_Amount")


mRNA<-melt(aggdata)
mRNA$Kit <-factor(mRNA$Kit, levels =c("Clontech","Illumina", "NEB","NEXTflex","Deduped", "Fivepercent"))
mRNA$variable<-factor(mRNA$variable, levels= c("mRNA","Mito", "rRNA", "tRNA", "snRNA", "CD_box","HACA_box", "scaRNA", "piRNA"))
mRNA$Input_Amount<-factor(mRNA$Input_Amount, levels= c("100","250","500", "1000", "1500", "2000"))
ggplot(mRNA, aes(x = Kit, y = value, color = Kit)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 0, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(.~variable)+scale_fill_manual(values=cols)+scale_color_manual(values=cols)

ggplot(mRNA, aes(x = variable, y = value, color = Kit)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(.~Kit)+scale_fill_manual(values=cols)+scale_color_manual(values=cols)

ggplot(mRNA, aes(x = variable, y = value, color = Kit)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(Kit~Input_Amount)+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +ggtitle("Percent of reads mapping to other RNAs") +labs(y="Percent of reads", x ="none")

pdf(file =here("Figures/Raw_plots/Fig.3.b.pdf"),width=10,height=7)
ggplot(mRNA, aes(x = variable, y = value, color = Kit)) +geom_boxplot( aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 20),axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 20), strip.text.y = element_text(size = 18))+facet_grid(Kit~Input_Amount)+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +ggtitle("Percent of reads mapping to other RNAs") +labs(y="Percent of reads", x ="none")
dev.off()

# this looks strange... think I need to aggregate data first
ggplot(mRNA, aes(x = variable, y = value, color = Kit, group = variable)) +geom_bar(stat  = "identity", position = "identity", aes(y =value, fill = Kit), col = "black") +theme(axis.title.x=element_blank(), axis.text.x=element_text(size = 14, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 20), axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 20))+facet_grid(Input_Amount~Kit)+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +ggtitle("Percent of reads mapping to other RNAs") +labs(y="Percent of reads", x ="none")




pdf(file =here("Figures/Raw_plots/Fig.3.b.pdf"),width=10,height=7)

ggplot(mRNA, aes(x = variable, y = value, color = Kit, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), strip.text.x = element_text(size = 15), strip.text.y = element_text(size = 15),legend.position = "NULL")+facet_grid(Input_Amount~Kit)+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +labs(y="Percent of reads", x ="none")
dev.off()

ggplot(mRNA, aes(x = variable, y = value, color = Kit, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), strip.text.x = element_text(size = 15), strip.text.y = element_text(size = 15),legend.position = "NULL")+facet_grid(Kit~Input_Amount, scales="free")+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +labs(y="Percent of reads", x ="none")



ggplot(mRNA, aes(x = Input_Amount, y = value, color = Kit, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), strip.text.x = element_text(size = 15), strip.text.y = element_text(size = 15),legend.position = "NULL")+facet_grid(variable~Kit)+scale_fill_manual(values=cols)+scale_color_manual(values=cols)  +labs(y="Percent of reads", x ="none")



mRNA$variable<-factor(mRNA$variable, levels= c("rRNA","mRNA", "tRNA", "piRNA", "Mito","CD_box","snRNA", "HACA_box", "scaRNA"))

ggplot(mRNA, aes(x = Kit, y = value, color = Kit, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), strip.text.x = element_text(size = 13), strip.text.y = element_text(size = 13),legend.position = "NULL")+facet_grid(variable~Input_Amount, scales="free")+scale_fill_manual(values=cols)+scale_color_manual(values=cols)  +labs(y="Percent of reads", x ="none")


ggplot(mRNA, aes(x = Input_Amount, y = value, color = Kit, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit), color = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 15),axis.title=element_text(size = 20), strip.text.x = element_text(size = 15), strip.text.y = element_text(size = 15),legend.position = "NULL")+facet_grid(Kit~variable)+scale_fill_manual(values=cols)+scale_color_manual(values=cols)  +labs(y="Percent of reads", x ="none")


#angled labels
ggplot(mRNA, aes(x = Input_Amount, y = value, color = Kit, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 20),axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 20), strip.text.y = element_text(size = 18, angle = 360),legend.position = "NULL")+facet_grid(variable~Kit)+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +ggtitle("Percent of reads mapping to other RNAs") +labs(y="Percent of reads", x ="none")


ggplot(mRNA, aes(x = Input_Amount, y = value, color = Kit, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 13, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 20),axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 12), strip.text.y = element_text(size = 12),legend.position = "NULL")+facet_grid(variable~Kit)+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +ggtitle("Percent of reads mapping to other RNAs") +labs(y="Percent of reads", x ="none")

##probably dont need this anymore
# RNAs_1000ng <-RNAs[which(RNAs$Input_Amount == "1000"),]
# otherRNA_1000nglist<-split.data.frame(RNAs_1000ng, f =RNAs_1000ng$Kit)
# Clontech<-data.frame("Clontech" =colMeans(otherRNA_1000nglist$Clontech[3:11]))
# Illumina<-data.frame("Illumina" =colMeans(otherRNA_1000nglist$Illumina[3:11]))
# NEB<-data.frame("NEB" =colMeans(otherRNA_1000nglist$NEB[3:11]))
# NEXTflex<-data.frame("NEXTflex" =colMeans(otherRNA_1000nglist$NEXTflex[3:11]))
# otherRNA<-cbind(Clontech, Illumina, NEB, NEXTflex)
# otherRNA$RNAs <- rownames(otherRNA)
# otherRNA <-melt(otherRNA)
# otherRNA$RNAs<-factor(otherRNA$RNAs, levels= c("rRNA","mRNA", "tRNA", "piRNA", "Mito","CD_box","snRNA", "HACA_box", "scaRNA"))
# #cols <-c(rep(cols[1], 9), rep(cols[2], 9), rep(cols[3], 9), rep(cols[4], 9))
# pdf(file =here("Figures/Raw_plots/Fig.3.b.pdf"),width=6,height=4.5)

mRNA<-mRNA[which(mRNA$Input_Amount =="1000"),]
mRNA$variable<-factor(mRNA$variable, levels= c("rRNA","mRNA", "tRNA", "piRNA", "Mito","CD_box","snRNA", "HACA_box", "scaRNA"))
ggplot(mRNA, aes(x = variable, y = value, color = Kit, width=.7)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit), col = "black") +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 18, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 20),axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 20), strip.text.y = element_text(size = 18), legend.position = "NULL")+facet_grid(.~Kit)+scale_fill_manual(values=cols)+scale_color_manual(values=cols) +ggtitle("Percent of reads mapping to other RNAs") +labs(y="Percent of reads", x ="none")


```

Just1000ng - other RNAs
```{r}
RNAs <-RNAs[grep("1000", RNAs$Input_Amount),]
RNAs <-RNAs[grep("1000", RNAs$Input_Amount),]
RNAs <-RNAs[-grep("miRNA", colnames(RNAs))]
RNAs <-RNAs[-grep("hairpin", colnames(RNAs))]
mRNA<-melt(RNAs)
mRNA$Kit <-factor(mRNA$Kit, levels =c("Clontech","Illumina", "NEB","NEXTflex","Deduped", "Fivepercent"))

ggplot(mRNA, aes(x = Kit, y = value, color = Kit)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 0, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(.~variable)+scale_fill_manual(values=cols)+scale_color_manual(values=cols)
ggplot(mRNA, aes(x = variable, y = value, color = Kit)) +geom_bar(stat  = "identity", position = "dodge",width = 1, aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 60,hjust = 1, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(.~Kit)+scale_fill_manual(values=cols)+scale_color_manual(values=cols)
```

Dividing up

```{r, eval = FALSE}
library("here")
library("ggplot2")
library("reshape2")

RNAs <-RNAs[grep("1000", RNAs$Input_Amount),]
RNAs1<-data.frame(RNAs$Kit, RNAs$Input_Amount, RNAs$mRNA, RNAs$Mitochondria, RNAs$rRNA, RNAs$tRNA_hg19)
colnames(RNAs1)<-(c("Method", "starting_amt", "mRNA", "Mito","rRNA", "tRNA"))
mRNA<-melt(RNAs1)
ggplot(mRNA, aes(x = variable, y = value, color = Method)) +geom_bar(stat  = "identity", position = "dodge", aes(y =value, fill = Method)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(starting_amt~.)

RNAs2<-cbind(RNAs$Kit, RNAs$Input_Amount, RNAs$mRNA, RNAs$Mitochondria, RNAs$rRNA, RNAs$tRNA_hg19)
RNAs3
mRNA<-melt(RNAs)
mRNA$Kit <-factor(mRNA$Kit, levels =c("Clontech","Illumina", "NEB","NEXTflex","Deduped", "Fivepercent"))

```

```{r, eval = FALSE}
RNAs <-RNAs[-grep("Deduped", RNAs$Kit),]
RNAs <-RNAs[-grep("Fivepercent", RNAs$Kit),]


mRNA<-melt(RNAs)
mRNA$Kit <-factor(mRNA$Kit, levels =c("Clontech","Illumina", "NEB","NEXTflex"))

ggplot(mRNA, aes(x = variable, y = value, color = Kit)) +geom_bar(stat  = "identity", position = "dodge", aes(y =value, fill = Kit)) +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10))+facet_grid(Input_Amount~.) + ylim(0,100)

total_mapped<-data.frame(rowSums(RNAs[3:11]))
RNAs$Perc_mapped <- total_mapped$rowSums.RNAs.3.11..
RNAs$Perc_unmapped <- 100-total_mapped$rowSums.RNAs.3.11..

### why is Deduped not 100%???? miRNA

mRNA<-melt(RNAs)
mRNA$Kit <-factor(mRNA$Kit, levels =c("Clontech","Illumina", "NEB","NEXTflex"))

ggplot(mRNA, aes(x = variable, y = value, color = Kit)) +geom_bar(stat  = "identity", position = "dodge", aes(y =value, fill = Kit)) +theme(axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10)) +labs(y = "Percent of reads", title = "RNA representation across Kits", x = "Sequence Length")+facet_grid(Input_Amount~.) + ylim(0,100)


### add adapter sequences dimer mapping?

ggplot(mRNA, aes(x = variable, y = value, color = Kit)) +geom_point() +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10)) +facet_grid(.~Input_Amount) +coord_flip()

ggplot(mRNA, aes(x = variable, y = value, color = Kit)) +geom_point() +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10)) +facet_grid(Input_Amount~.)+coord_flip()

ggplot(mRNA, aes(x = variable, y = value, color = Kit))+ geom_bar(stat = "identity", aes(y =value, fill = Kit))  +theme( axis.title.x=element_blank(), axis.text.x=element_text(size = 10, angle = 90, face = "bold", colour = "black"), axis.text.y=element_text(size = 10)) +facet_grid(.~Input_Amount) +coord_flip()



```

