---
title: "Correlationplot"
author: "Carrie Wright"
date: "6/18/2018"
output: html_document
---
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

load the data
```{r, eval=TRUE, echo=FALSE}
library(here)
Pheno<- read.table(here("Complete_data/Pheno.txt"), header = TRUE)
miR_counts<-read.table(here("Complete_data/miR.Counts.csv"), header = TRUE, sep = ",")

rownames(miR_counts)<- miR_counts$miRNA#make miRNA rownames
miR_counts<-miR_counts[,2:length(colnames(miR_counts))]#remove miRNA col

colnames(miR_counts)<-gsub("directional_dedupped|directional_deduped", "Deduped", colnames(miR_counts))
colnames(miR_counts)<-gsub("NEXT_", "NEXTflex_", colnames(miR_counts))
miRNAtotal<-t(miR_counts[1,])#extract the total miRNA counts... in case we want them
miR_counts<-miR_counts[-1,]#remove total miRNA counts row

Pheno$File<-gsub("NEXTflex_deduped", "Deduped", Pheno$File)
Pheno$Kit<-gsub("NEXTflex_deduped", "Deduped", Pheno$Kit)
Pheno$TriplicateGroup<-gsub("NEXTflex_deduped", "Deduped", Pheno$TriplicateGroup)
Pheno$miRNAtotal <-miRNAtotal
 
identical(as.character(Pheno$File), colnames(data.frame(miR_counts))) ###Check that these match 
identical(rownames(miRNAtotal), Pheno$File)
#remove extra samples
Pheno<- Pheno[-2,]
miR_counts<- miR_counts[,-2]

#remove Fivepercent
#Pheno<- Pheno[1:81,]
#miR_counts<-miR_counts[,1:81]
#Pheno<- Pheno[-6,]
#miR_counts<-miR_counts[,-6]
# #remove Deduped
#   Pheno<- Pheno[1:62,]
# miR_counts<-miR_counts[,1:62]
# Pheno<- Pheno[-5,]
# miR_counts<-miR_counts[,-5]
miR_counts<- miR_counts[which(Pheno$startingAmt =="1000")]
Pheno <- Pheno[which(Pheno$startingAmt =="1000"),]#grab just the 1000ng samples of both batches
```

 
 

###DESeq2
```{r, eval=TRUE,warning=FALSE, message=FALSE, echo =FALSE}
library(DESeq2)
dds<-DESeqDataSetFromMatrix(countData = miR_counts, colData = Pheno, design = ~ Kit)
dds <- estimateSizeFactors(dds)
norm_miR_counts<-data.frame(counts(dds, normalized = TRUE))
dim(norm_miR_counts)
```

###genefilter
```{r, eval=TRUE, echo = FALSE}
library(genefilter)

# poverafun <- genefilter::pOverA(p = 1, A = 1)#at least one raw read in all samples #379
# ffun <- filterfun(poverafun)
# index <- genefilter(miR_counts, ffun)
# thresh_miR_counts <- norm_miR_counts[index,]
# dim(thresh_miR_counts)


#thresh for removing zeros in all methods:
thresh_miR_counts <-norm_miR_counts[which(rowSums(norm_miR_counts)>0),]
```





###correlationplot
```{r, eval = TRUE}
library(GGally)
set.seed(42)
get_log <- function(x){log2(x +1)}
log_thresh_miR_counts <-sapply(thresh_miR_counts, get_log)
rownames(log_thresh_miR_counts)<-rownames(thresh_miR_counts)
thresh_miR_counts<-log_thresh_miR_counts
thresh_miR_counts<-data.frame(thresh_miR_counts)
# make average for miR_Counts by kit
split_kit <- list() 
for(i in Pheno$Kit) { 
  split_kit[[i]] <- data.frame(thresh_miR_counts[which(Pheno$Kit==i)]) #raw counts
} 

avg_1000ng <-lapply(split_kit,rowMeans)
avg_1000ng<-data.frame(avg_1000ng)
pdf(file =here("Figures/Raw_plots/correlation.pdf"),width=10.5,height=7)
ggpairs(avg_1000ng)
dev.off()
# estimated density in diagonal
```

##MA plot
```{r}
library(ggplot2)

data_1000ng<-as.matrix(avg_1000ng)

make_plot<-function(dfma){ggplot(dfma, aes(x = A, y = M)) +geom_hline(color = "blue3", yintercept = 0, size=2)+ geom_point(size = 3)+ stat_smooth(se = FALSE, method = "loess", color = "red", size=2)+ ylim(c(-7,7))+  xlim(4,18)+theme(axis.text.x = element_text(size = 40), axis.text.y = element_text(size = 40), axis.title.x = element_text(size = 40), axis.title.y = element_text(size = 40))}

make_MA_df <- function(x, y){
M = x - y
A = (x + y)/2
dfma <<- data.frame(A, M)}

##### manually
make_MA_df(x =avg_1000ng$Clontech, y = avg_1000ng$Illumina)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Clontech_Illumina.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$Clontech, y = avg_1000ng$NEB)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Clontech_NEB.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()


make_MA_df(x =avg_1000ng$Clontech, y = avg_1000ng$NEXTflex)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Clontech_NEXTflex.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$Clontech, y = avg_1000ng$Deduped)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Clontech_Deduped.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$Clontech, y = avg_1000ng$Fivepercent)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Clontech_Fivepercent.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$Illumina, y = avg_1000ng$NEB)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Illumina_NEB.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$Illumina, y = avg_1000ng$NEXTflex)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Illumina_NEXTflex.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$Illumina, y = avg_1000ng$Deduped)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Illumina_Deduped.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$Illumina, y = avg_1000ng$Fivepercent)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Illumina_Fivepercent.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$NEB, y = avg_1000ng$NEXTflex)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_NEB_NEXTflex.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$NEB, y = avg_1000ng$Deduped)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_NEB_Deduped.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$NEB, y = avg_1000ng$Fivepercent)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_NEB_Fivepercent.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$NEXTflex, y = avg_1000ng$Deduped)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_NEXTflex_Deduped.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$NEXTflex, y = avg_1000ng$Fivepercent)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_NEXTflex_Fivepercent.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()

make_MA_df(x =avg_1000ng$Deduped, y = avg_1000ng$Fivepercent)
pdf(file =here("Figures/Raw_plots/MA_plots/MA_Deduped_Fivepercent.pdf"),width=6,height=4, onefile=FALSE)
make_plot(dfma)
dev.off()
```

### to get to catplots
```{r}
ranks<-data.frame(sapply(-avg_1000ng, rank, ties.method = "random"))#ranked so 1 is the highest
# rownames(ranks_error)<-rownames(errorData_testdf)
# Clontech_ranks <-(ranks_error[grep("Clontech", colnames(ranks_error))])
# Illumina_ranks <-(ranks_error[grep("Illumina", colnames(ranks_error))])
# NEB_ranks <-(ranks_error[grep("NEB", colnames(ranks_error))])
# NEXTflex_ranks <-(ranks_error[grep("NEXTflex", colnames(ranks_error))])
# Deduped_ranks <-(ranks_error[grep("Deduped", colnames(ranks_error))])
# Fivepercent_ranks <-(ranks_error[grep("Fivepercent", colnames(ranks_error))])
# ranked_miRNA<-list()

cor(ranks$Clontech, ranks$Illumina, method = "kendall")
cor(ranks$Clontech, ranks$Illumina)
cor(ranks$Clontech, ranks$NEB)
cor(ranks$Clontech, ranks$NEXTflex)
cor(ranks$Clontech, ranks$Deduped)
cor(ranks$Clontech, ranks$Fivepercent)
cor(ranks$Illumina, ranks$NEB)
cor(ranks$Illumina, ranks$NEXTflex)
cor(ranks$Illumina, ranks$Deduped)
cor(ranks$Illumina, ranks$Fivepercent)

cor(ranks$NEB, ranks$NEXTflex)
cor(ranks$NEB, ranks$Deduped)
cor(ranks$NEB, ranks$Fivepercent)

cor(ranks$NEXTflex, ranks$Deduped)
cor(ranks$NEXTflex, ranks$Fivepercent)

cor(ranks$Deduped, ranks$Fivepercent)

pdf(file =here("Figures/Raw_plots/correlation_ranks.pdf"),width=10.5,height=7)
ggpairs(ranks)
dev.off()



```

# top 10 analysis

```{r}
library(VennDiagram)

Clontech_top <- data.frame(rownames(avg_1000ng)[order(-rank(avg_1000ng$Clontech))])
Illumina_top <- data.frame(rownames(avg_1000ng)[order(-rank(avg_1000ng$Illumina))])
NEB_top <- data.frame(rownames(avg_1000ng)[order(-rank(avg_1000ng$NEB))])
NEXTflex_top <- data.frame(rownames(avg_1000ng)[order(-rank(avg_1000ng$NEXTflex))])
Deduped_top <- data.frame(rownames(avg_1000ng)[order(-rank(avg_1000ng$Deduped))])
Fivepercent_top <- data.frame(rownames(avg_1000ng)[order(-rank(avg_1000ng$Fivepercent))])
Top <- data.frame(Clontech_top, Illumina_top, NEB_top, NEXTflex_top, Deduped_top, Fivepercent_top)
colnames(Top)<-c("Clontech", "Illumina", "NEB", "NEXTflex", "Deduped", "Fivepercent")
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

n = 6
cols = gg_color_hue(n)
cols <-cols[1:5]
Top <-Top[1:5,]

vp_1000 <- venn.diagram(Top[1:5], fill = c(cols), alpha = 0.5, filename = NULL, margin = 0.2, cat.dist = c(.3,.3,.3, .3, .3))

# cols <-cols[1:4]
# vp_1000 <- venn.diagram(Top[1:4], fill = c(cols), alpha = 0.5, filename = NULL, margin = 0.2, cat.dist = c(.3,.3,.3, .3))

```
pdf(file =here("Figures/Raw_plots/Venn_of_top_expressed_new_thresh.pdf"),width=6,height=6,onefile=FALSE)
grid.draw(vp_1000);
dev.off()

top overlaps
```{r}
Top <- data.frame(Clontech_top, Illumina_top, NEB_top, NEXTflex_top, Deduped_top, Fivepercent_top)
colnames(Top)<-c("Clontech", "Illumina", "NEB", "NEXTflex", "Deduped", "Fivepercent")
# I could do this for each triplicate instead of the average... and then I could actually do stats on it... 
Top5<-Top[1:5,]#1
Top10<-Top[1:10,]#2
Top20<-Top[1:20,]#6
Top50<-Top[1:50,]#24
Top100<-Top[1:100,]#48
get_num_unique <-function(x){(length(unique(x)))}
merged_top5<-data.frame(unlist(Top5))

overlap_data<-data.frame(overlaps =c(1,2,6,24,48), top_amount= c(5,10,20,50,100), percent_overlap = c(20, 20, 30, 48, 48))
```




```{r}
library(UpSetR)
upset(fromList(Top), order.by = "freq")




startend <- UpSetR:::FindStartEnd(data)
  first.col <- startend[1]
  last.col <- startend[2]

  if(color.pal == 1){
    palette <- c("#1F77B4", "#FF7F0E", "#2CA02C", "#D62728", "#9467BD", "#8C564B", "#E377C2",
                 "#7F7F7F", "#BCBD22", "#17BECF")
  } else{
    palette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00",
                 "#CC79A7")
  }

  if(is.null(intersections) == F){
    Set_names <- unique((unlist(intersections)))
    Sets_to_remove <- UpSetR:::Remove(data, first.col, last.col, Set_names)
    New_data <- UpSetR:::Wanted(data, Sets_to_remove)
    Num_of_set <- UpSetR:::Number_of_sets(Set_names)
    if(keep.order == F){
      Set_names <- UpSetR:::order_sets(New_data, Set_names)
    }
    All_Freqs <- UpSetR:::specific_intersections(data, first.col, last.col, intersections, order.by, group.by, decreasing,
                                        cutoff, main.bar.color, Set_names)
  } else if(is.null(intersections) == T){
    Set_names <- sets
    if(is.null(Set_names) == T || length(Set_names) == 0 ){
      Set_names <- UpSetR:::FindMostFreq(data, first.col, last.col, nsets)
    }
    Sets_to_remove <- UpSetR:::Remove(data, first.col, last.col, Set_names)
    New_data <- UpSetR:::Wanted(data, Sets_to_remove)
    Num_of_set <- UpSetR:::Number_of_sets(Set_names)
    if(keep.order == F){
    Set_names <- UpSetR:::order_sets(New_data, Set_names)
    }
    All_Freqs <- UpSetR:::Counter(New_data, Num_of_set, first.col, Set_names, nintersects, main.bar.color,
                         order.by, group.by, cutoff, empty.intersections, decreasing)
  }
  Matrix_setup <- UpSetR:::Create_matrix(All_Freqs)
  labels <- UpSetR:::Make_labels(Matrix_setup)
  #Chose NA to represent NULL case as result of NA being inserted when at least one contained both x and y
  #i.e. if one custom plot had both x and y, and others had only x, the y's for the other plots were NA
  #if I decided to make the NULL case (all x and no y, or vice versa), there would have been alot more if/else statements
  #NA can be indexed so that we still get the non NA y aesthetics on correct plot. NULL cant be indexed.
  att.x <- c(); att.y <- c();
  if(is.null(attribute.plots) == F){
    for(i in seq_along(attribute.plots$plots)){
      if(length(attribute.plots$plots[[i]]$x) != 0){
        att.x[i] <- attribute.plots$plots[[i]]$x
      }
      else if(length(attribute.plots$plots[[i]]$x) == 0){
        att.x[i] <- NA
      }
      if(length(attribute.plots$plots[[i]]$y) != 0){
        att.y[i] <- attribute.plots$plots[[i]]$y
      }
      else if(length(attribute.plots$plots[[i]]$y) == 0){
        att.y[i] <- NA
      }
    }
  }

  BoxPlots <- NULL
  if(is.null(boxplot.summary) == F){
    BoxData <- UpSetR:::IntersectionBoxPlot(All_Freqs, New_data, first.col, Set_names)
    BoxPlots <- list()
    for(i in seq_along(boxplot.summary)){
      BoxPlots[[i]] <- UpSetR:::BoxPlotsPlot(BoxData, boxplot.summary[i], att.color)
    }
  }

  customAttDat <- NULL
  customQBar <- NULL
  Intersection <- NULL
  Element <- NULL
  legend <- NULL
  EBar_data <- NULL
  if(is.null(queries) == F){
    custom.queries <- UpSetR:::SeperateQueries(queries, 2, palette)
    customDat <- UpSetR:::customQueries(New_data, custom.queries, Set_names)
    legend <- UpSetR:::GuideGenerator(queries, palette)
    legend <- UpSetR:::Make_legend(legend)
    if(is.null(att.x) == F && is.null(customDat) == F){
      customAttDat <- UpSetR:::CustomAttData(customDat, Set_names)
    }
    customQBar <- UpSetR:::customQueriesBar(customDat, Set_names, All_Freqs, custom.queries)
  }
  if(is.null(queries) == F){
    Intersection <- UpSetR:::SeperateQueries(queries, 1, palette)
    Matrix_col <- UpSetR:::intersects(QuerieInterData, Intersection, New_data, first.col, Num_of_set,
                             All_Freqs, expression, Set_names, palette)
    Element <- UpSetR:::SeperateQueries(queries, 1, palette)
    EBar_data <-UpSetR:::ElemBarDat(Element, New_data, first.col, expression, Set_names,palette, All_Freqs)
  } else{
    Matrix_col <- NULL
  }
  
  Matrix_layout <- UpSetR:::Create_layout(Matrix_setup, matrix.color, Matrix_col, matrix.dot.alpha)












Make_matrix_plot <- function(Mat_data,Set_size_data, Main_bar_data, point_size, line_size, text_scale, labels,
                             shading_data, shade_alpha){

  if(length(text_scale) == 1){
    name_size_scale <- text_scale
  }
  if(length(text_scale) > 1 && length(text_scale) <= 6){
    name_size_scale <- text_scale[5]
  }
  
  Mat_data$line_col <- 'black'

  Matrix_plot <- (ggplot()
                  + theme(panel.background = element_rect(fill = "white"),
                          plot.margin=unit(c(-0.2,0.5,0.5,0.5), "lines"),
                          axis.text.x = element_blank(),
                          axis.ticks.x = element_blank(),
                          axis.ticks.y = element_blank(),
                          axis.text.y = element_text(colour = "gray0",
                                                     size = 7*name_size_scale, hjust = 0.4),
                          panel.grid.major = element_blank(),
                          panel.grid.minor = element_blank())
                  + xlab(NULL) + ylab("   ")
                  + scale_y_continuous(breaks = c(1:nrow(Set_size_data)),
                                       limits = c(0.5,(nrow(Set_size_data) +0.5)),
                                       labels = labels, expand = c(0,0))
                  + scale_x_continuous(limits = c(0,(nrow(Main_bar_data)+1 )), expand = c(0,0))
                  + geom_rect(data = shading_data, aes_string(xmin = "min", xmax = "max",
                                                              ymin = "y_min", ymax = "y_max"),
                              fill = shading_data$shade_color, alpha = shade_alpha)
                  + geom_line(data= Mat_data, aes_string(group = "Intersection", x="x", y="y",
                                                         colour = "line_col"), size = line_size)
                 + geom_point(data= Mat_data, aes_string(x= "x", y= "y"), colour = Mat_data$color,
                     size= point_size, alpha = Mat_data$alpha, shape=16)
                  + scale_color_identity())
  Matrix_plot <- ggplot_gtable(ggplot_build(Matrix_plot))
  return(Matrix_plot)
}


## Initial inputs on the first example
movies <- read.csv( system.file("extdata", "movies.csv", package = "UpSetR"), 
                    header=T, sep=";" )

## comma -> semicolon
data = movies; sets = c("Action", "Comedy", "Drama"); 
      order.by="degree"; matrix.color="blue"; point.size=5;
      sets.bar.color=c("maroon","blue","orange")

  for(i in 1:3) {
      j <- which(Matrix_layout$y == i & Matrix_layout$value == 1)
      if(length(j) > 0) Matrix_layout$color[j] <- c("maroon","blue","orange")[i]
  }





```









#### catplots
```{r}
library(ffpe)
#1000ng -rel to Clontech
test <-c(rep(0,1660))
ranks[[7]] <- c(rep(0,1660))

library(RColorBrewer)
trop = cols <- brewer.pal(9, "Set1")

catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(ranks[[i]],ranks[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Similarity_Clontech.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to Clontech",xlab="Rank", cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(900,0.5,legend=c("Clontech_vs_Illumina","Clontech_vs_NEB", "Clontech_vs_NEXTflex","Clontech_vs_Deduped","Clontech_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)
dev.off()

#1000ng -rel to NEXTflex
ranks <-ranks[c("NEXTflex", "Illumina", "NEB", "Clontech", "Deduped", "Fivepercent", "V7")]
catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(ranks[[i]], ranks[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Similarity_NEXTflex.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to NEXTflex",xlab="Rank", cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(900,0.5,legend=c("NEXTflex_vs_Illumina","NEXTflex_vs_NEB", "NEXTflex_vs_Clontech","NEXTflex_vs_Deduped","NEXTflex_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)
dev.off()

#1000ng -rel to Illumina
ranks <-ranks[c("Illumina","Clontech","NEB", "NEXTflex", "Deduped", "Fivepercent", "V7")]
catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(ranks[[i]], ranks[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Similarity_Illumina.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to Illumina",xlab="Rank", cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(900,0.5,legend=c("Illumina_vs_Clontech","Illumina_vs_NEB", "Illumina_vs_NEXTflex","Illumina_vs_Deduped","Illumina_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)
dev.off()

#1000ng -rel to NEB
ranks <-ranks[c("NEB","Clontech","Illumina", "NEXTflex", "Deduped", "Fivepercent", "V7")]

catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(ranks[[i]], ranks[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Similarity_NEB.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to NEB",xlab="Rank", cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(900,0.5,legend=c("NEB_vs_Clontech","NEB_vs_Illumina", "NEB_vs_NEXTflex","NEB_vs_Deduped","NEB_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)
dev.off()

#1000ng -rel to Deduped
ranks <-ranks[c("Deduped","Clontech","Illumina", "NEB","NEXTflex", "Fivepercent", "V7")]

catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(ranks[[i]],ranks[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Similarity_Deduped.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to Deduped",xlab="Rank", cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(900,0.5,legend=c("Deduped_vs_Clontech","Deduped_vs_Illumina","Deduped_vs_NEB", "Deduped_vs_NEXTflex","Deduped_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)

dev.off()


#1000ng -rel to Fivepercent
ranks <-ranks[c("Fivepercent","Clontech","Illumina", "NEB","NEXTflex", "Deduped", "V7")]

catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(ranks[[i]], ranks[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Similarity_Fivepercent.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to Fivepercent",xlab="Rank", cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(900,0.5,legend=c("Fivepercent_vs_Clontech","Fivepercent_vs_Illumina","Fivepercent_vs_NEB", "Fivepercent_vs_NEXTflex","Fivepercent_vs_Deduped", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)

dev.off()
```

###Dendrogram to see how data clusters after normalization of counts
```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
library(rafalib)
library(dendextend)
library(reshape2)


yGene <-as.matrix(thresh_miR_counts)
miRNAc <- hclust(dist(t(yGene)))
pdD<-Pheno
pdD$Kit<-as.factor(pdD$Kit)
pdD$TriplicateGroup<-as.factor(pdD$TriplicateGroup)
par(mar=c(10,2,3,0))
colors<-as.numeric(pdD$Kit)

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

n = 6
cols = gg_color_hue(n)
repeat_colors <-function(x){rep(x,6)}
cols2 <- lapply(cols, repeat_colors)
cols2<-unlist(cols2)
cols2 <-cols2[order(miRNAc$order)]

myplclust(miRNAc, labels=pdD$TriplicateGroup,lab.col=(cols2), main = "Counts cluster by library prep kit")

```


