---
title: "Kit_batch_analysis_07_27_17"
author: "carriewright"
date: "7/27/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/home/carrie/Kit_comparison/kit_comparison/")
```

###First need to load the data using the raw counts and the RPM values from miRge
```{r, echo=FALSE}
miR_counts<-read.table("/home/carrie/UMI/after_UMI_tools_Nextflex_kitcomparison/UMI_NEXTflex_and_all_kits_1000ng/All_combined_1000ng/miR.Counts.csv", header = TRUE, sep = ",") 
rownames(miR_counts)<- miR_counts$miRNA#make miRNA rownames
miR_counts<-miR_counts[,2:length(colnames(miR_counts))]#remove miRNA col
miR_counts<-miR_counts[-1,]#remove miRNA col

miR_RPMs<-read.table("/home/carrie/UMI/after_UMI_tools_Nextflex_kitcomparison/UMI_NEXTflex_and_all_kits_1000ng/All_combined_1000ng/miR.RPM.csv", header = TRUE, sep = ",")
rownames(miR_RPMs)<- miR_RPMs$miRNA#make miRNA rownames
miR_RPMs<-miR_RPMs[,2:length(colnames(miR_RPMs))]#remove miRNA col
Pheno<- read.table("/home/carrie/UMI/Pheno_1000ng_full", header = T)
```

###Make dendrogram to see how data clusters
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(rafalib)
library(dendextend)
yGene<-as.matrix(miR_RPMs)
miRNAc <- hclust(dist(t(yGene)))
pdD<-Pheno
par(mar=c(10,2,3,0))
myplclust(miRNAc, labels=pdD$TriplicateGroup,lab.col=(as.numeric(pdD$Kit)))
#newcol<-recode(colors,"1= '5'")
#myplclust(miRNAc, labels=pdD$TriplicateGroup,lab.col=(as.numeric(newcol)))
#colors = as.numeric(pdD$Kit)
#newcol<-replace(colors, 4, '5')
```

###Load the full repro data with the nomissmatch option (no UMI deduped data)
```{r}
#path to data was "/home/carrie/miRge/HiSeq_newrun_nomissmatch_alltogether/")
nodedup_miR_RPM<-read.table( "nodeduped.miR.RPM.csv", header = T, sep = ",")### This is the RPM data output from miRge
rownames(nodedup_miR_RPM) <- nodedup_miR_RPM$miRNA#make miRNA rownames
nodedup_miR_RPM <- nodedup_miR_RPM[,2:length(colnames(nodedup_miR_RPM))]#remove miRNA col
nodedup_miR_RPM_brain_accbatch <- nodedup_miR_RPM[grep("mm0_acc" , colnames(nodedup_miR_RPM))]#grab just the synthetic data
nodedup_miR_RPM_brain_reprobatch <- nodedup_miR_RPM[grep("mm0_acc" , colnames(nodedup_miR_RPM), invert = TRUE)]#remove the accuracy data - to just have the human brain data
```

###Load just the nextflex UMI data
```{r}
#path to data was "/UMI/after_UMI_tools_Nextflex_kitcomparison/NextFlex_across_amounts/NEXT_all_combined"
dedup_miR_RPM_brain<-read.table( "deduped.miR.RPM.csv", header = T, sep = ",")# this is only brain data
rownames(dedup_miR_RPM_brain) <- dedup_miR_RPM_brain$miRNA#make miRNA rownames
dedup_miR_RPM_brain <- dedup_miR_RPM_brain[,2:length(colnames(dedup_miR_RPM_brain))]#remove miRNA col
#path to data was "/home/carrie/UMI/after_UMI_tools_Nextflex_kitcomparison/Synthetic_accuracy/NEXT_sample4_combined/miRge.1491773214"
dedup_miR_RPM_synth <- read.table( "deduped.miR.RPM.acc.csv", header = T, sep = ",")
rownames(dedup_miR_RPM_synth) <- dedup_miR_RPM_synth$miRNA#make miRNA rownames
dedup_miR_RPM_synth <- dedup_miR_RPM_synth[,2:length(colnames(dedup_miR_RPM_synth))]#remove miRNA col
```
###Test that data is ok
Make sure the nextflex raw data is the same in both sets of files (deduped vs nodeduped)
```{r}
identical(nodedup_miR_RPM_synth$)
```

```{r, eval=FALSE, echo=FALSE}
pd<-read.table("/home/carrie/miRge/kit_comparison_pd.txt", header = TRUE)
readinfo<-readHTMLTable("/home/carrie/miRge/HiSeq_newrun_nomissmatch_alltogether/report.html", stringsAsFactors = FALSE, which = 1, header = TRUE)# which is for reading the first table
indextokeep<-seq(1,nrow(readinfo), 5)#get rid of nans
readinfo<-readinfo[indextokeep,]# Total Input Reads == miRNAreads + othernoncoding+ mRNA+ Hairpin reads + remaining... what is remaining???mapped to genome but not these??#what are the filtered miRNA reads?
# readinfo<-as.data.frame(readinfo[grep("mm0_acc_Illumina_trimmed.4_R1.fq" , readinfo$`File name(s)`, invert = TRUE),  ,FALSE])
# readinfo<-as.data.frame(readinfo[grep("mm0_acc_NEB_trimmed.4_R1.fq" , readinfo$`File name(s)`, invert = TRUE),  ,FALSE])
# readinfo<-as.data.frame(readinfo[grep("mm0_acc_NEXT_trimmed.4_R1.fq" , readinfo$`File name(s)`, invert = TRUE),  ,FALSE])
totalmapped<-as.data.frame(as.numeric(readinfo$`Total Input Reads`))
colnames(totalmapped)<-"totalmapped"
pd$totalmapped<- totalmapped$totalmapped
counts<-read.table("/home/carrie/miRge/HiSeq_newrun_nomissmatch_alltogether/miR.Counts.csv", header = TRUE, sep = ",")
miRNAtotal<-as.data.frame(t(counts[1,][2:length(colnames(counts))]))
# miRNAtotal<-as.data.frame(miRNAtotal[grep("mm0_acc_Illumina_trimmed.4_R1.fq" , rownames(miRNAtotal), invert = TRUE),  ,FALSE])
# miRNAtotal<-as.data.frame(miRNAtotal[grep("mm0_acc_NEB_trimmed.4_R1.fq" , rownames(miRNAtotal), invert = TRUE),  ,FALSE])
# miRNAtotal<-as.data.frame(miRNAtotal[grep("mm0_acc_NEXT_trimmed.4_R1.fq" , rownames(miRNAtotal), invert = TRUE),  ,FALSE])
pd$miRNAtotal <- miRNAtotal$`1`###this is the filtered miRNA counts###need to figure out what that means
```


