---
title: "synth_stats_may30"
author: "Carrie Wright"
date: "May 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r}
library(here)
load(here("normalized_synth.rmd"))
```

###FUNCTIONS to get ttests results and output nicely
```{r, echo = TRUE, eval=TRUE}
library(dplyr)
get_test_names <- function(data){
  test_names <<- data.frame(combn(names(data), m= 2))
}

get_test_results<- function(data,test_names) {
  tresults<<-list()
  tested_names1<<-list()
  tested_names2<<-list()
  for(i in names(test_names)){
    #tested_names[[i]]<<-(test_names[i][,1])
    Kit1<-data.frame(select(data, colnames(data)[colnames(data) %in% test_names[i][1,]]))
    Kit2<-data.frame(select(data, colnames(data)[colnames(data) %in% test_names[i][2,]]))
    tested_names1[[i]]<<-colnames(Kit1)
    tested_names2[[i]]<<-colnames(Kit2)
    colnames(Kit1)<-c("error")
    colnames(Kit2)<-c("error")
    tresults[[i]]<<-t.test(x=Kit1$error, y=Kit2$error, paired = TRUE) ### may have messed things up adding paired = TRUE previously had more ))
    tested_kits <<-paste0(tested_names1, "&", tested_names2)
  }
}

get_ttestStats<- function(x) {
  #print(length(test_names))
  c(t =format(x$statistic, digits = 2),
    df = format(x$parameter, digits = 0),
    p.value = format(x$p.value, scientific = TRUE, digits = 2),
    bonferroni_thresh = format(.05/length(test_names), digits = 2),
    sig = ifelse(x$p.value<(.05/length(test_names)), "yes", "no"))
}

#get_lmStats <-function(x) {
#  c(p=x$coefficients[2,4], scientific = TRUE, digits =2)
#}
```
overall stats
```{r}
library(reshape2)
get_test_names(data = error_synth)
#sink(here(synthlog.txt"))
get_test_results(test_names = test_names, data = error_synth)
#sink()
ttestStats<-data.frame(lapply(tresults, get_ttestStats))

colnames(ttestStats)<-tested_kits

ttestStats
synth <-melt(error_synth)
fit = lm(synth$value ~ synth$variable)
anova(fit)

```




Base stats
```{r}

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last <- data.frame(x =lastStuff(str=seqs$RNA, 1))####uncomment to get last n bases
rownames(seqs_last)<-seqs$name
seqs_first <-data.frame(x =strtrim(seqs$RNA, c(1)))###uncomment to get first n bases and comment next line
rownames(seqs_first)<-seqs$name

errorData_toplot<-log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
errorData_toplot<-data.frame(lapply(errorData_toplot, get_perc))
errorLast<-cbind(seqs_last, errorData_toplot)
errorFirst<-cbind(seqs_first, errorData_toplot)

# errorLast <-cbind(seqs_last, error_synth[1:6])
# errorFirst<-cbind(seqs_first, error_synth[1:6])
#  get_perc<-function(x) {(x/mean(x))*100}
# errorLast<-data.frame(abs_errorLast[1], lapply(abs_errorLast[2:7], get_perc))
#  errorFirst<-data.frame(abs_errorFirst[1], lapply(abs_errorFirst[2:7], get_perc))

firstdata <-melt(errorFirst)
lastdata <-melt(errorLast)

split_last <- list() 
for(i in lastdata$variable) { 
  split_last[[i]] <- data.frame(lastdata[which(lastdata$variable==i),])
} 

split_first <- list() 
for(i in firstdata$variable) { 
  split_first[[i]] <- data.frame(firstdata[which(firstdata$variable==i),])
} 
run_anova<-function(x){anova(lm(x[[3]]~x[[1]]))}
last_f_stats<-lapply(split_last,run_anova)
first_f_stats<-lapply(split_first,run_anova)
get_fStats<- function(x) {
  #print(length(test_names))
  c(F =format(x$`F value`, digits = 0),
    p.value = format(x$`Pr(>F)`, scientific = TRUE, digits = 2),
    bonferroni_thresh = format(.05/6, digits = 2),
    sig = ifelse(x$`Pr(>F)`<(.05/6), "yes", "no"))
}
last_f_stats<-data.frame(t(data.frame(lapply(last_f_stats, get_fStats))))
first_f_stats<-data.frame(t(data.frame(lapply(first_f_stats, get_fStats))))

first_f_stats
last_f_stats

#geom_text(data = last_f_stats, aes(y = 25, label = p.value1, family = "serif"), 
          #color = 'blue',  parse = TRUE)
get_base_results<- function(data,kit_name) {
  tested_names1 <<-list()
  tested_names2 <<-list()
  tresults<<-list()
  for(i in names(data)){
    Kit_of_interest<-data[colnames(data) %in% kit_name]
    Adata <-Kit_of_interest[which(data$x =="A"),]
    Cdata <-Kit_of_interest[which(data$x =="C"),]
    Gdata <-Kit_of_interest[which(data$x =="G"),]
    Tdata <-Kit_of_interest[which(data$x =="U"),]
    BaseData <<- list(Adata, Cdata, Gdata, Tdata)
    names(BaseData) <<-c("A", "C", "G", "U")
  }
  test_names <- get_test_names(data = BaseData)
  for(i in names(test_names)){ 
    Base1<-data.frame(BaseData[names(BaseData) %in% test_names[i][1,]])
    Base2<-data.frame(BaseData[names(BaseData) %in% test_names[i][2,]])
    tested_names1[[i]]<<-colnames(Base1)
    tested_names2[[i]]<<-colnames(Base2)    
    colnames(Base1)<-c("error")
    colnames(Base2)<-c("error")
    tresults[[i]]<<-t.test(x=Base1$error, y=Base2$error, paired = FALSE)
    tested_kits <<-paste0(tested_names1, "&", tested_names2)
  }}

####Firstbase
get_base_results(data = errorFirst, kit_name = "Clontech")
ttestStats<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats)<-tested_kits
ttestStats

get_base_results(data = errorFirst, kit_name = "Fivepercent")
ttestStats<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats)<-tested_kits
ttestStats

####Lastbase

get_base_results(data = errorLast, kit_name = "Illumina")
ttestStats<-data.frame(lapply(tresults, get_ttestStats))
colnames(ttestStats)<-tested_kits
ttestStats

anova(lm(split_last$Illumina$value ~ split_last$Illumina$x))
```

LengthStats

```{r}
library(limma)
library(broom)

GC <-seqs$length

expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)

colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)
model_summary<-lapply(model_stats, summary)
lapply(model_summary, glance)


run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
quad_model_stats<-lapply(split_data,run_model_quad)
quad_summary<-lapply(quad_model_stats, summary)
lapply(quad_summary, glance)

anova(model_stats$Clontech, quad_model_stats$Clontech)
anova(model_stats$Illumina, quad_model_stats$Illumina)
anova(model_stats$NEB, quad_model_stats$NEB)#only one not sig - thus poly model better for other kits
anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)
anova(model_stats$Deduped, quad_model_stats$Deduped)
anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)
#this should do the same
#poly_model <- function(x){summary(lm(x[[3]]~I(x[[1]]^2))}
#poly_model <- function(x){summary(lm(x[[3]]~poly(x[[1]],2, raw = TRUE))}
#poly_model_stats<-lapply(split_data,poly_model )
#poly_model_stats
summary(model_stats$NEB)#not sig for linear
```


https://www.theanalysisfactor.com/r-tutorial-4/
GCStats
```{r}
library(limma)
#want to know for each kit- is there a sig difference in detection of miRNAS of  different lengths ?
#or
#want to know for each length is there a sig difference bewteen kits... This could also be interesting
GC <-seqs$GC
#abs_error<-cbind(factor(GC), error_synth[1:6])
#abs_error<-data.frame(abs_error[1], lapply(abs_error[2:7], get_perc))


expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)

colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)

#length_f_stats<-data.frame(t(data.frame(lapply(length_f_stats, get_fStats))))

#lapply(model_stats, summary)

run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
quad_model_stats<-lapply(split_data,run_model_quad)
lapply(quad_model_stats, summary)

#sig better fit for all kits
anova(model_stats$Clontech, quad_model_stats$Clontech)
anova(model_stats$Illumina, quad_model_stats$Illumina)
anova(model_stats$NEB, quad_model_stats$NEB)
anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)
anova(model_stats$Deduped, quad_model_stats$Deduped)
anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)
table(round(GC, digits = 1))
```

FoldStats
```{r}
library(limma)
#want to know for each kit- is there a sig difference in detection of miRNAS of  different lengths ?
#or
#want to know for each length is there a sig difference bewteen kits... This could also be interesting
GC <-seqs$FoldG
#abs_error<-cbind(factor(GC), error_synth[1:6])


expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)
colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 

#run_model <-function(x){(lm(x[[3]]~x[[1]]))}
run_model <-function(x){(lm(x$value~x$factor))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)

run_model <-function(x){(cor(x$value,x$factor))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)

lapply(model_stats, anova_stats)
# run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
# quad_model_stats<-lapply(split_data,run_model_quad)
# lapply(quad_model_stats, summary)

# NOT sig better fit for all kits
# anova(model_stats$Clontech, quad_model_stats$Clontech)
# anova(model_stats$Illumina, quad_model_stats$Illumina)
# anova(model_stats$NEB, quad_model_stats$NEB)
# anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)
# anova(model_stats$Deduped, quad_model_stats$Deduped)
# anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)

table(round(GC, digits = 1))
```



repeat stats
Repeats
```{r}
TTTT<-sapply(gregexpr("TTTT", seqs$x), function(x) sum(x != -1))
GGGG<-sapply(gregexpr("GGGG", seqs$x), function(x) sum(x != -1))
AAAA<-sapply(gregexpr("AAAA", seqs$x), function(x) sum(x != -1))
CCCC<-sapply(gregexpr("CCCC", seqs$x), function(x) sum(x != -1))
patterns <- c("TT", "GG", "CC", "AA")
dublets <- sapply(gregexpr(paste(patterns,collapse="|"), 
                        seqs$x), function(x) sum(x != -1))
anyT<-sapply(gregexpr("T", seqs$x), function(x) sum(x != -1))
anyG<-sapply(gregexpr("G", seqs$x), function(x) sum(x != -1))
anyC<-sapply(gregexpr("C", seqs$x), function(x) sum(x != -1))
anyA<-sapply(gregexpr("A", seqs$x), function(x) sum(x != -1))
```

Dublets
```{r}
library(limma)
#want to know for each kit- is there a sig difference in detection of miRNAS of  different lengths ?
#or
#want to know for each length is there a sig difference bewteen kits... This could also be interesting
GC <-dublets
#abs_error<-cbind(factor(GC), error_synth[1:6])

#abs_error<-cbind(factor(GC), log2(miRge_synth +1))

expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)
colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)


run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
quad_model_stats<-lapply(split_data,run_model_quad)

 anova(model_stats$Clontech, quad_model_stats$Clontech)
 anova(model_stats$Illumina, quad_model_stats$Illumina)
 anova(model_stats$NEB, quad_model_stats$NEB)
 anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)# sig 
 anova(model_stats$Deduped, quad_model_stats$Deduped)# sig
 anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)
 summary(quad_model_stats$Deduped)
 summary(quad_model_stats$NEXTflex)
 table(GC)
```

quad
```{r}
library(limma)
#want to know for each kit- is there a sig difference in detection of miRNAS of  different lengths ?
#or
#want to know for each length is there a sig difference bewteen kits... This could also be interesting
GC <-TTTT
#abs_error<-cbind(factor(GC), error_synth[1:6])

#abs_error<-cbind(factor(GC), log2(miRge_synth +1))

expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)
colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)


run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
quad_model_stats<-lapply(split_data,run_model_quad)

 anova(model_stats$Clontech, quad_model_stats$Clontech)
 anova(model_stats$Illumina, quad_model_stats$Illumina)
 anova(model_stats$NEB, quad_model_stats$NEB)
 anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)# sig
 anova(model_stats$Deduped, quad_model_stats$Deduped)# sig
 anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)

 table(GC)
```

anyT
```{r}
library(limma)
#want to know for each kit- is there a sig difference in detection of miRNAS of  different lengths ?
#or
#want to know for each length is there a sig difference bewteen kits... This could also be interesting
GC <-anyT
#abs_error<-cbind(factor(GC), error_synth[1:6])

#abs_error<-cbind(factor(GC), log2(miRge_synth +1))

expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)
colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)


run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
quad_model_stats<-lapply(split_data,run_model_quad)

 anova(model_stats$Clontech, quad_model_stats$Clontech)
 anova(model_stats$Illumina, quad_model_stats$Illumina)#sig but less good - explains less
 anova(model_stats$NEB, quad_model_stats$NEB)
 anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)
 anova(model_stats$Deduped, quad_model_stats$Deduped)
 anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)

 table(GC)
```

anyA
```{r}
library(limma)

GC <-anyA

expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)
colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)


run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
quad_model_stats<-lapply(split_data,run_model_quad)

 anova(model_stats$Clontech, quad_model_stats$Clontech)#not sig
 anova(model_stats$Illumina, quad_model_stats$Illumina)
 anova(model_stats$NEB, quad_model_stats$NEB)
 anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)
 anova(model_stats$Deduped, quad_model_stats$Deduped)
 anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)

 table(GC)
```
anyG
```{r}
library(limma)

GC <-anyG

expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)
colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)


run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
quad_model_stats<-lapply(split_data,run_model_quad)

 anova(model_stats$Clontech, quad_model_stats$Clontech)#not sig
 anova(model_stats$Illumina, quad_model_stats$Illumina)
 anova(model_stats$NEB, quad_model_stats$NEB)
 anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)
 anova(model_stats$Deduped, quad_model_stats$Deduped)
 anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)

 table(GC)
```

anyC
```{r}
library(limma)

GC <-anyC

expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)
colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)
run_model <-function(x){(cor(x[[3]], x[[1]]))}
model_stats<-lapply(split_data,run_model)

run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
quad_model_stats<-lapply(split_data,run_model_quad)
lapply(quad_model_stats, summary)
 anova(model_stats$Clontech, quad_model_stats$Clontech)
 anova(model_stats$Illumina, quad_model_stats$Illumina)#sig
 anova(model_stats$NEB, quad_model_stats$NEB)#sig
 anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)
 anova(model_stats$Deduped, quad_model_stats$Deduped)
 anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)

 table(GC)
```

anyquad
```{r}
library(limma)

GC <-(TTTT+ CCCC+ GGGG+ AAAA)

expression <- log2(miRge_synth+1)
get_perc<-function(x) {(x/mean(x))*100}
express_perc<-data.frame(lapply(expression, get_perc))
abs_error<-cbind(factor(GC), express_perc)
colnames(abs_error)[1] <-"factor"

factordata<-melt(abs_error)
colnames(factordata)<-c("factor", "kit", "value")
factordata$factor <-as.numeric(as.character(factordata$factor))
factordata$quad_Fact <-factordata$factor^2

 split_data <- list() 

for(i in factordata$kit) { 
  split_data[[i]] <- data.frame(factordata[which(factordata$kit==i),])
} 
 run_model <-function(x){(lm(x[[3]]~x[[1]]))}
model_stats<-lapply(split_data,run_model)
lapply(model_stats, summary)


#run_model_quad <-function(x){(lm(x[[3]]~x[[1]] +x[[4]]))}
#quad_model_stats<-lapply(split_data,run_model_quad)

 anova(model_stats$Clontech, quad_model_stats$Clontech)#notsig
 anova(model_stats$Illumina, quad_model_stats$Illumina)#notsig
 anova(model_stats$NEB, quad_model_stats$NEB)#notsig
 anova(model_stats$NEXTflex, quad_model_stats$NEXTflex)#notsig
 anova(model_stats$Deduped, quad_model_stats$Deduped)#notsig
 anova(model_stats$Fivepercent, quad_model_stats$Fivepercent)#notsig

 table(GC)
```
Variance Plot
```{r}
library(ggplot2)
yGene<-as.matrix(log2(miRge_synth+1))

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last <- data.frame(x =lastStuff(str=seqs$RNA, 1))####uncomment to get last n bases
rownames(seqs_last)<-seqs$name
seqs_first <-data.frame(x =strtrim(seqs$RNA, c(1)))###uncomment to get first n bases and comment next line
rownames(seqs_first)<-seqs$name

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last_two <- data.frame(x =lastStuff(str=seqs$RNA, 2))####uncomment to get last n bases
rownames(seqs_last)<-seqs$name
seqs_first_two <-data.frame(x =strtrim(seqs$RNA, c(2)))###uncomment to get first n bases and comment next line
rownames(seqs_first)<-seqs$name

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last_three<- data.frame(x =lastStuff(str=seqs$RNA, 3))####uncomment to get last n bases
rownames(seqs_last)<-seqs$name
seqs_first_three <-data.frame(x =strtrim(seqs$RNA, c(3)))###uncomment to get first n bases and comment next line
rownames(seqs_first)<-seqs$name

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last_four <- data.frame(x =lastStuff(str=seqs$RNA, 4))####uncomment to get last n bases
rownames(seqs_last)<-seqs$name
seqs_first_four <-data.frame(x =strtrim(seqs$RNA, c(4)))###uncomment to get first n bases and comment next line
rownames(seqs_first)<-seqs$name

#seqs$FoldG<-errorFoldG$FoldG
pd<-seqs
pd$First_base <-seqs_first$x
pd$First_2_bases <-seqs_first_two$x
pd$First_3_bases <-seqs_first_three$x
pd$First_4_bases <-seqs_first_four$x
pd$Last_base <-seqs_last$x
pd$Last_2_bases <-seqs_last_two$x
pd$Last_3_bases <-seqs_last_three$x
pd$Last_4_bases <-seqs_last_four$x
pd$TTTT <- TTTT
pd$CCCC <- CCCC
pd$GGGG <- GGGG
pd$AAAA <- AAAA
pd$rep <- (TTTT+ CCCC+ GGGG+ AAAA)
pd$dublets <-dublets
pd$anT <- anyT
pd$anyC <-anyC
pd$anyG <- anyG
pd$anyA <- anyA

#modFull = model.matrix(~GC + length +FoldG + First_base + Last_base +TTTT + CCCC + GGGG +AAAA, data=pd)


varCompAnalysis = apply(t(yGene),1,function(y) {
  if(runif(1) < 1e-4) cat(".")
  fit = lm(y ~ GC + length +FoldG + First_base + Last_base+ First_2_bases + First_4_bases + Last_2_bases + Last_4_bases +rep + dublets+ AAAA+ TTTT + CCCC + GGGG +anyT +anyC + anyG + anyA, data=pd)
  full = anova(fit)
  fullSS =full$"Sum Sq"
  signif(cbind(full,PctExp=fullSS/
                 sum(fullSS)*100),3)
})



varexp <-do.call(rbind, lapply(varCompAnalysis, data.frame))
labels_varexp <- data.frame(do.call('rbind', strsplit(as.character(rownames(varexp)),'.',fixed=TRUE)))
colnames(labels_varexp)<-c("Kit", "variable")
#colnames(labels_varexp)<-c("variable")
VarExp<-cbind(labels_varexp,varexp$PctExp)
#VarExp$variable <- factor(VarExp$variable,levels = c("GC" ,"length" ,"FoldG" , "First_base", "Last_base", "First_2_bases", "First_4_bases", "Last_2_bases" , "Last_4_bases", "rep", "dublets", "AAAA", "TTTT", "CCCC", "GGGG", 'Residuals'),ordered = TRUE)
VarExp$KitF <- factor(VarExp$Kit,levels = c("Clontech", "Illumina", "NEB", "NEXTflex", "Deduped", "Fivepercent"), ordered = TRUE)
plotfull<-ggplot(VarExp, aes(factor(variable), varexp$PctExp)) + geom_boxplot(aes(fill = "black"), notch = TRUE, outlier.shape=NA) +facet_grid(~KitF)
plotfull +ggtitle("Percent of Variance Explained by Influential Factors") +
  labs(y="Percent of Variance Explained", x ="none") + 
  scale_fill_manual(values = c("black"))+
  theme(legend.position = "none", axis.title.x=element_blank(), axis.text.y=element_text(size = 30, angle = 90, face = "bold"), axis.text.x=element_text(size = 10, angle = 20, face = "bold", colour = "black"),
        axis.title.y=element_text(size=20), plot.title = element_text(size = 30, face = "bold"))

variance <- lapply(log2(miRge_synth+1), var)
boxplot(variance)
expression <-log2(miRge_synth+1)
#if F is greater than one its worse for first kit
get_test_names(expression)
get_var_results <-function(data,test_names) {
  tresults<<-list()
  tested_names1<<-list()
  tested_names2<<-list()
  for(i in names(test_names)){
    #tested_names[[i]]<<-(test_names[i][,1])
    Kit1<-data.frame(select(data, colnames(data)[colnames(data) %in% test_names[i][1,]]))
    Kit2<-data.frame(select(data, colnames(data)[colnames(data) %in% test_names[i][2,]]))
    tested_names1[[i]]<<-colnames(Kit1)
    tested_names2[[i]]<<-colnames(Kit2)
    colnames(Kit1)<-c("error")
    colnames(Kit2)<-c("error")
    tresults[[i]]<<-var.test(x=Kit1$error, y=Kit2$error) ### may have messed things up adding paired = TRUE previously had more ))
    tested_kits <<-paste0(tested_names1, "&", tested_names2)
  }
}
get_var_results(data =expression, test_names = test_names)
varStats<-data.frame(lapply(tresults, get_ttestStats))
colnames(varStats)<-tested_kits
varStats

VarExp[which(VarExp$variable == "First_base"),]
VarExp[which(VarExp$variable == "Last_base"),]
VarExp[grep("First", VarExp$variable),]
VarExp[grep("Last", VarExp$variable),]

#pheatmap(VarExp)
```


```{r, eval=FALSE}
library(pheatmap)
varexp2 <-do.call(cbind, lapply(varCompAnalysis, data.frame))
varexp_PctExp<-varexp2[grep("PctExp", colnames(varexp2))]
colnames(varexp_PctExp) <- c("Clontech","Illumina","NEB","NEXTflex","Deduped", "Fivepercent")
#varexp_PctExp<- varexp_PctExp[-grep("Residuals",rownames(varexp_PctExp)),]
# 
# pheatmap(varexp_PctExp, main = "varexp", cluster_cols = FALSE, cluster_rows = FALSE)
# myBreaks<-seq(to=round(max(53))+3, from = min(varexp_PctExp), length.out = paletteLength*(max(sorted_aggdata))/20)
# myColor<-colorRampPalette(c("white","red"))(length(myBreaks))### change for white
# #myColor<-c(myColorbelow, myColorabove)
# pheatmap(varexp_PctExp, breaks = myBreaks, color = myColor)


varexp2 <-do.call(cbind, lapply(varCompAnalysis, data.frame))
varexp_PctExp<-varexp2[grep("PctExp", colnames(varexp2))]
colnames(varexp_PctExp) <- c("Clontech","Illumina","NEB","NEXTflex","Deduped", "Fivepercent")
varexp_PctExp<- varexp_PctExp[-grep("Residuals",rownames(varexp_PctExp)),]
varexp_PctExp<- varexp_PctExp[-grep("Last_4_bases",rownames(varexp_PctExp)),]
varexp_PctExp<- varexp_PctExp[-grep("First_4_bases",rownames(varexp_PctExp)),]
pheatmap(varexp_PctExp, main = "varexp", cluster_cols = FALSE, cluster_rows = FALSE)
myBreaks<-seq(to=round(max(varexp_PctExp))+3, from = min(varexp_PctExp), length.out = paletteLength*(max(sorted_aggdata))/20)
myColor<-colorRampPalette(c("white","red"))(length(myBreaks))### change for white
#myColor<-c(myColorbelow, myColorabove)
pheatmap(varexp_PctExp, breaks = myBreaks, color = myColor, cluster_rows = FALSE, cluster_cols = FALSE, main ="Contribution of factors to sequence detection variance")


####weighted by overall variance by multiplying by overall variance...
# varexp2 <-do.call(cbind, lapply(varCompAnalysis, data.frame))
# varexp_PctExp<-varexp2[grep("PctExp", colnames(varexp2))]
# colnames(varexp_PctExp) <- c("Clontech","Illumina","NEB","NEXTflex","Deduped", "Fivepercent")
# varexp_PctExp<-varexp_PctExp*variance
# varexp_PctExp<- varexp_PctExp[-grep("Residuals",rownames(varexp_PctExp)),]
# #varexp_PctExp<- varexp_PctExp[-grep("Last_4_bases",rownames(varexp_PctExp)),]
# pheatmap(varexp_PctExp, main = "varexp", cluster_cols = FALSE, cluster_rows = FALSE)
# myBreaks<-seq(to=round(max(varexp_PctExp))+3, from = min(varexp_PctExp), length.out = paletteLength*(max(sorted_aggdata))/20)
# myColor<-colorRampPalette(c("white","red"))(length(myBreaks))### change for white
# #myColor<-c(myColorbelow, myColorabove)
# pheatmap(varexp_PctExp, breaks = myBreaks, main ="Contribution of factors to sequence detection variance", color = myColor, row_cols = FALSE)

####weighted by overall variance by multiplying by kit variance and dividing by mean of all kit variance
varexp2 <-do.call(cbind, lapply(varCompAnalysis, data.frame))
varexp_PctExp<-varexp2[grep("PctExp", colnames(varexp2))]
colnames(varexp_PctExp) <- c("Clontech","Illumina","NEB","NEXTflex","Deduped", "Fivepercent")
varexp_PctExp2<-((varexp_PctExp*variance)/mean(unlist(variance)))
varexp_PctExp2<- varexp_PctExp2[-grep("Residuals",rownames(varexp_PctExp2)),]
varexp_PctExp2<- varexp_PctExp2[-grep("Last_4_bases",rownames(varexp_PctExp2)),]
varexp_PctExp2<- varexp_PctExp2[-grep("First_4_bases",rownames(varexp_PctExp2)),]
pheatmap(varexp_PctExp2, main = "varexp", cluster_cols = FALSE)
myBreaks<-seq(to=round(max(varexp_PctExp2)+2), from = min(varexp_PctExp2), length.out = paletteLength*(max(varexp_PctExp2))/2)
myColor<-colorRampPalette(c("white","red"))(length(myBreaks))### change for white
pheatmap(varexp_PctExp2, breaks = myBreaks, color = myColor, main = "Contribution of factors to sequence detection variance \n weighted by overall variance for each kit", cluster_cols = FALSE, cluster_rows = FALSE)
```