---
title: "SD"
author: "Carrie Wright"
date: "6/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r, eval=TRUE, echo=FALSE}
#library(edgeR)
library(here)

load(here("Complete_data/IsomiR_data/Pheno.rda"))
Pheno1000 <- Pheno[which(Pheno$startingAmt =="1000"),]
miR_counts<-read.table(here("Complete_data/miR.Counts.csv"), header = TRUE, sep = ",")

rownames(miR_counts)<- miR_counts$miRNA#make miRNA rownames
miR_counts<-miR_counts[,2:length(colnames(miR_counts))]#remove miRNA col
miRNAtotal<-t(miR_counts[1,])#extract the total miRNA counts... in case we want them
miR_counts<-miR_counts[-1,]#remove total miRNA counts row
miR_counts<-miR_counts[,-2]#remove extra Clontech sample

colnames(miR_counts)<-gsub("directional_dedupped|directional_deduped", "Deduped", colnames(miR_counts))
colnames(miR_counts)<-gsub("Five_double", "Fivepercent", colnames(miR_counts))

Pheno1000$Kit<-gsub("Five_double", "Fivepercent", Pheno1000$Kit)
Pheno1000$File<-gsub("Five_double", "Fivepercent", Pheno1000$File)

Pheno1000$File<-gsub("directional_deduped", "Deduped", Pheno1000$File)
Pheno1000$Kit<-gsub("NEXTflex_deduped", "Deduped", Pheno1000$Kit)
Pheno1000$TriplicateGroup<-gsub("directional_deduped", "Deduped", Pheno1000$TriplicateGroup)
miR_1000_raw <- data.frame(miR_counts[,which(Pheno$startingAmt == "1000")])
 
load(here("hsa_miRNA_info.rda"))

```


###DESeq2
```{r, eval=TRUE,warning=FALSE, message=FALSE, echo =FALSE}
library(DESeq2)
dds<-DESeqDataSetFromMatrix(countData = miR_1000_raw, colData = Pheno1000, design = ~ File)
dds <- estimateSizeFactors(dds)
norm_miR_1000<-data.frame(counts(dds, normalized = TRUE))
dim(norm_miR_1000)
```

```{r}
###split the data by kit
split_kit <- list() 
for(i in Pheno1000$Kit) { 
  split_kit[[i]] <- data.frame(norm_miR_1000[which(Pheno1000$Kit==i)])
} 
str(split_kit)
```





```{r}
###genefilter
library(genefilter)

poverafun <- genefilter::pOverA(p = 1, A = 10)#at least 10 normalized reads in all samples of the set... 
ffun <- filterfun(poverafun)
genefilt_fun<- function(x){genefilter(x, ffun)}
thresh<-lapply(split_kit, genefilt_fun)

split_kit_thresh <-list()
split_kit_thresh$Clontech<-split_kit$Clontech[thresh$Clontech,]
split_kit_thresh$Illumina<-split_kit$Illumina[thresh$Illumina,]
split_kit_thresh$NEB<-split_kit$NEB[thresh$NEB,]
split_kit_thresh$NEXTflex<-split_kit$NEXTflex[thresh$NEXTflex,]
split_kit_thresh$Deduped<-split_kit$Deduped[thresh$Deduped,]
split_kit_thresh$Fivepercent<-split_kit$Fivepercent[thresh$Fivepercent,]


```



Functions
```{r}

library(dplyr)
library(compute.es)

get_test_names <- function(data){
  test_names <<- data.frame(combn(unique(names(data)), m= 2))
}

get_test_results<- function(data,test_names, pairedvalue) {
  tresults<<-list()
  tested_names1<<-list()
  tested_names2<<-list()
  length_kits <<-list()
  for(i in names(test_names)){
    Kit1 <<-data[which(names(data) %in% test_names[i][1,])]
    Kit2 <<-data[which(names(data) %in% test_names[i][2,])]
    tested_names1[[i]]<<-names(data)[names(data) %in% test_names[i][1,]]
    tested_names2[[i]]<<-names(data)[names(data) %in% test_names[i][2,]]
    tresults[[i]]<<-t.test(x=Kit1[[1]], y=Kit2[[1]], paired = pairedvalue)
    tested_kits <<-paste0(tested_names1, "&", tested_names2)
    length_kits[[i]]<<-c(length(Kit1[[1]]), length(Kit2[[1]]))
  }
}

get_ttestStats<- function(x, tested_kits) {
  c(t =format(x$statistic, digits = 2),
    df = format(x$parameter, digits = 0),
    p.value = format(x$p.value, scientific = TRUE, digits = 2),
    bonferroni.threshold = format(.05/length(test_names), digits = 2),
    sig = ifelse(x$p.value<(.05/length(test_names)), "yes", "no"),
    mean_1st_method = format(x$estimate[[1]], digits =2), 
    mean_2nd_method =format(x$estimate[[2]], digits =2))
}

get_t.es.g <- function(ts){
  t.es.g <<-list()
  for(i in names(length_kits)){
  t.es.g[[i]]<<-tes(ts[[i]]$statistic, n.1 = length_kits[i][[1]][1], n.2 = length_kits[i][[1]][2])$g
  }
}


get_perc_diff <-function(data) {
  percresults<<-list()
  tested_names1<<-list()
  tested_names2<<-list()
  tested_kits<<-list()
  for(i in names(test_names)){
    percresults[[i]]<<-((data[ which(names(data)==test_names[i][1,])]-data[ which(names(data)==test_names[i][2,])]))/ data[ which(names(data)==test_names[i][2,])]*100
    tested_names1[[i]]<<-test_names[i][1,]
    tested_names2[[i]]<<-test_names[i][2,]
    tested_kits[[i]] <<-paste0(tested_names1[[i]], "&", tested_names2[[i]])
    }
}


```



Error from Means

```{r}
library(reshape2)
library(ggplot2)
forerrorData<-list()

forerrorData$Clontech[[1]]<-rowMeans(split_kit_thresh$Clontech[2:4])
forerrorData$Clontech[[2]]<-rowMeans(split_kit_thresh$Clontech[1])
names(forerrorData$Clontech) <-c("Batch1", "Batch2")

forerrorData$Illumina[[1]]<-rowMeans(split_kit_thresh$Illumina[2:4])
forerrorData$Illumina[[2]]<-rowMeans(split_kit_thresh$Illumina[1])
names(forerrorData$Illumina) <-c("Batch1", "Batch2")

forerrorData$NEB[[1]]<-rowMeans(split_kit_thresh$NEB[2:4])
forerrorData$NEB[[2]]<-rowMeans(split_kit_thresh$NEB[1])
names(forerrorData$NEB) <-c("Batch1", "Batch2")

forerrorData$NEXTflex[[1]]<-rowMeans(split_kit_thresh$NEXTflex[2:4])
forerrorData$NEXTflex[[2]]<-rowMeans(split_kit_thresh$NEXTflex[1])
names(forerrorData$NEXTflex) <-c("Batch1", "Batch2")

forerrorData$Deduped[[1]]<-rowMeans(split_kit_thresh$Deduped[2:4])
forerrorData$Deduped[[2]]<-rowMeans(split_kit_thresh$Deduped[1])
names(forerrorData$Deduped) <-c("Batch1", "Batch2")

forerrorData$Fivepercent[[1]]<-rowMeans(split_kit_thresh$Fivepercent[2:4])
forerrorData$Fivepercent[[2]]<-rowMeans(split_kit_thresh$Fivepercent[1])
names(forerrorData$Fivepercent) <-c("Batch1", "Batch2")
forerrorData <-lapply(forerrorData, data.frame)


get_error <-function(x){log2(abs(x - rowMeans(x))+1)}
error_from_mean <-lapply(forerrorData, get_error)
getone <- function(x){rowMeans(x)}
error_from_mean <- lapply(error_from_mean, getone)

ERRORm <-melt(error_from_mean)

#anova
anova(lm(ERRORm$value~ERRORm$L1)) #F =40.798 df =5 p = <2.2e-16
library(sjstats)
anova_stats(anova(lm(ERRORm$value~ERRORm$L1))) # omega-= 0.071
#higher t is worse because we are using variance 
get_test_names(error_from_mean)
get_test_results(data = error_from_mean, test_names = test_names, pairedvalue = FALSE)
ttestStats_across<-data.frame(lapply(tresults, get_ttestStats, tested_kits = tested_kits))
colnames(ttestStats_across)<-tested_kits
t(ttestStats_across)




Means<-unlist(lapply(error_from_mean, mean))
test_names<-names(Means)
get_perc_diff <-function(data) {
  percresults<<-list()
  tested_names1<<-list()
  tested_names2<<-list()
  tested_kits<<-list()
  for(i in names(test_names)){
    percresults[[i]]<<-((data[ which(names(data)==test_names[i][1,])]-data[ which(names(data)==test_names[i][2,])]))/ data[ which(names(data)==test_names[i][2,])]*100
    tested_names1[[i]]<<-test_names[i][1,]
    tested_names2[[i]]<<-test_names[i][2,]
    tested_kits[[i]] <<-paste0(tested_names1[[i]], "&", tested_names2[[i]])
    }
}
get_test_names(Means)
get_perc_diff(data = Means)
perc_stats<-data.frame(percresults)
colnames(perc_stats)<-tested_kits
t(perc_stats)


get_t.es.g(ts = tresults)
 t(data.frame(t.es.g))

pdf(file =here("Figures/Raw_plots/batch_cons_not_Union.pdf"),width=3.8,height=4, onefile=FALSE)
ERRORm$L1<-factor(ERRORm$L1, levels = c("Clontech", "Illumina", "NEB", "NEXTflex", "Deduped", "Fivepercent"))
ggplot(ERRORm, aes(x = L1, y = value))+geom_jitter(aes(color = L1, alpha = 0.7), width = .3)+ geom_boxplot(notch =FALSE, outlier.shape = NA, varwidth = TRUE, position = position_dodge(1))+theme(legend.position = "none", axis.text.x = element_text(size =15, angle = 60, hjust = 1), axis.text.y = element_text(size =15, hjust = 1), axis.title.y=element_text(size = 17),axis.title.x = element_text(size = 0), plot.title = element_text(size = 20), strip.text.x = element_text(size = 20)) + labs( x= "Starting Amount", y = " Error from the Mean", title = " Inconsistency Across Batch")
dev.off()
```
```{r}
#Explanation of Variance Plot


Names_thresh<-intersect(intersect(intersect(intersect(intersect(rownames(forerrorData[[1]]), rownames(forerrorData[[2]])), rownames(forerrorData[[3]])), rownames(forerrorData[[4]])), rownames(forerrorData[[5]])), rownames(forerrorData[[6]]))

finding_rows<-function(x){x[rownames(x) %in% Names_thresh, , drop= FALSE]}

expression<- lapply(forerrorData, finding_rows)
expression <-(lapply(expression, log2))
Error <- lapply(error_from_mean, data.frame)
Error <-lapply(Error, finding_rows)
Error <- data.frame(Error)
names(Error)<- names(error_from_mean)

avg_Express <-data.frame(Clontech =rowMeans(expression$Clontech), Illumina = rowMeans(expression$Illumina), NEB = rowMeans(expression$NEB), NEXTflex = rowMeans(expression$NEXTflex), Deduped = rowMeans(expression$Deduped), Fivepercent = rowMeans(expression$Fivepercent))


load(here("hsa_miRNA_info.rda"))
seqs <- data.frame(seqs_human[which(seqs_human$name %in% Names_thresh),])
seqs <-seqs[order(seqs$name),]

interesction_seqs <- Names_thresh
Names_thresh[which(!Names_thresh %in% seqs_human$name)] #10 of the intersecting miRNAs are difficult to distinguish so miRge lumps together with multiple miRNA seq identities with varying gc, length etc... so these will be excluded.
avg_Express <- avg_Express[-which(!Names_thresh %in% seqs_human$name),]
Error<- Error[-which(!Names_thresh %in% seqs_human$name),]
identical(rownames(Error), rownames(avg_Express))

TTTT<-sapply(gregexpr("UUUU", seqs$seqs), function(x) sum(x != -1))
GGGG<-sapply(gregexpr("GGGG", seqs$seqs), function(x) sum(x != -1))
AAAA<-sapply(gregexpr("AAAA", seqs$seqs), function(x) sum(x != -1))
CCCC<-sapply(gregexpr("CCCC", seqs$seqs), function(x) sum(x != -1))
patterns <- c("UU", "GG", "CC", "AA")

duplets <- sapply(gregexpr(paste(patterns,collapse="|"), 
                        seqs$seqs), function(x) sum(x != -1))
anyT<-sapply(gregexpr("U", seqs$seqs), function(x) sum(x != -1))
anyG<-sapply(gregexpr("G", seqs$seqs), function(x) sum(x != -1))
anyC<-sapply(gregexpr("C", seqs$seqs), function(x) sum(x != -1))
anyA<-sapply(gregexpr("A", seqs$seqs), function(x) sum(x != -1))

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last <- data.frame(x =lastStuff(str=seqs$seqs, 1))####uncomment to get last n bases
seqs_first <-data.frame(x =strtrim(seqs$seqs, c(1)))###uncomment to get first n bases and comment next line

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last_two <- data.frame(x =lastStuff(str=seqs$seqs, 2))####uncomment to get last n bases
seqs_first_two <-data.frame(x =strtrim(seqs$seqs, c(2)))###uncomment to get first n bases and comment next line

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last_three<- data.frame(x =lastStuff(str=seqs$seqs, 3))####uncomment to get last n bases
seqs_first_three <-data.frame(x =strtrim(seqs$seqs, c(3)))###uncomment to get first n bases and comment next line

lastStuff<-function(str, n){result <-substr(str,(nchar(str)+1)-n,nchar(str))}
seqs_last_four <- data.frame(x =lastStuff(str=seqs$seqs, 4))####uncomment to get last n bases
seqs_first_four <-data.frame(x =strtrim(seqs$seqs, c(4)))###uncomment to get first n bases and comment next line

#seqs$FoldG<-errorFoldG$FoldG
pd<-seqs
pd$First_base <-seqs_first$x
pd$First_2_bases <-seqs_first_two$x
pd$First_3_bases <-seqs_first_three$x
pd$First_4_bases <-seqs_first_four$x
pd$Last_base <-seqs_last$x
pd$Last_2_bases <-seqs_last_two$x
pd$Last_3_bases <-seqs_last_three$x
pd$Last_4_bases <-seqs_last_four$x
pd$TTTT <- TTTT
pd$CCCC <- CCCC
pd$GGGG <- GGGG
pd$AAAA <- AAAA
pd$rep <- (TTTT+ CCCC+ GGGG+ AAAA)
pd$duplets <-duplets
pd$anyT <- anyT
pd$anyC <-anyC
pd$anyG <- anyG
pd$anyA <- anyA

Clontech_pd <-cbind(pd, avg_Express$Clontech)
Illumina_pd<-cbind(pd, avg_Express$Illumina)
NEB_pd<-cbind(pd, avg_Express$NEB)
NEXTflex_pd<-cbind(pd, avg_Express$NEXTflex)
Deduped_pd<-cbind(pd, avg_Express$Deduped)
Fivepercent_pd<-cbind(pd, avg_Express$Fivepercent)
```
####
run for each kit
```{r}
library(car)
#overall variance of error
variance <- lapply(Error, var)
boxplot(variance) # interesting the variance in error is really low for deduped - meaning error is more consistent across sequences

yGene <-as.matrix(Error$Clontech)

varCompAnalysis = apply(t(yGene),1,function(y) {
  if(runif(1) < 1e-4) cat(".")
  fit = lm(y ~ GC +length +FoldG + First_base + Last_base+ First_2_bases + First_4_bases + Last_2_bases + Last_4_bases +rep + duplets+ GGGG+ TTTT + CCCC + AAAA +anyA +anyC + anyG +anyT +avg_Express$Clontech, data=Clontech_pd)
  fit = lm(yGene ~avg_Express$Clontech+ GC+  + length +FoldG  +First_2_bases + Last_2_bases+ anyA + anyT + anyC + duplets + GGGG + TTTT + CCCC +AAAA , data=Clontech_pd, singular.ok = TRUE)
  full =Anova(fit, type = "II")
  fullSS =full$"Sum Sq"
  signif(cbind(full,PctExp=fullSS/
                 sum(fullSS)*100),3)
})
varexpclontech <-do.call(rbind, lapply(varCompAnalysis, data.frame))
###############
yGene <-as.matrix(Error$Illumina)

varCompAnalysis = apply(t(yGene),1,function(y) {
  if(runif(1) < 1e-4) cat(".")
  fit = lm(y ~ GC + length +FoldG + First_base + Last_base+ First_2_bases + First_4_bases + Last_2_bases + Last_4_bases +rep + duplets+ GGGG+ TTTT + CCCC + AAAA +anyA +anyC + anyG + anyT + avg_Express$Illumina , data=Illumina_pd)
  fit = lm(yGene ~avg_Express$Illumina+ GC+  + length +FoldG  +First_2_bases + Last_2_bases+ anyA + anyT + anyC + duplets + GGGG + TTTT + CCCC +AAAA , data=Illumina_pd, singular.ok = TRUE)
  full =Anova(fit, type = "II")
  fullSS =full$"Sum Sq"
  signif(cbind(full,PctExp=fullSS/
                 sum(fullSS)*100),3)
})
varexpIllumina <-do.call(rbind, lapply(varCompAnalysis, data.frame))
###############

yGene <-as.matrix(Error$NEB)

varCompAnalysis = apply(t(yGene),1,function(y) {
  if(runif(1) < 1e-4) cat(".")
  fit = lm(y ~ GC + length +FoldG + First_base + Last_base+ First_2_bases + First_4_bases + Last_2_bases + Last_4_bases +rep + duplets+ GGGG+ TTTT + CCCC + AAAA +anyA +anyC + anyG + anyT +avg_Express$NEB, data=NEB_pd)
  fit = lm(yGene ~avg_Express$NEB+ GC+  + length +FoldG  +First_2_bases + Last_2_bases+ anyA + anyT + anyC + duplets + GGGG + TTTT + CCCC +AAAA , data =NEB_pd, singular.ok = TRUE)
  full =Anova(fit, type = "II")
  fullSS =full$"Sum Sq"
  signif(cbind(full,PctExp=fullSS/
                 sum(fullSS)*100),3)
})
varexpNEB <-do.call(rbind, lapply(varCompAnalysis, data.frame))
###############
yGene <-as.matrix(Error$NEXTflex)

varCompAnalysis = apply(t(yGene),1,function(y) {
  if(runif(1) < 1e-4) cat(".")
  fit = lm(y ~ GC + length +FoldG + First_base + Last_base+ First_2_bases + First_4_bases + Last_2_bases + Last_4_bases +rep + duplets+ GGGG+ TTTT + CCCC + AAAA +anyA +anyC + anyG + anyT + avg_Express$NEXTflex, data=NEXTflex_pd)
  fit = lm(yGene ~avg_Express$NEXTflex+ GC+  + length +FoldG  +First_2_bases + Last_2_bases+ anyA + anyT + anyC + duplets + GGGG + TTTT + CCCC +AAAA , data=NEXTflex_pd, singular.ok = TRUE)
 full =Anova(fit, type = "II")
  fullSS =full$"Sum Sq"
  signif(cbind(full,PctExp=fullSS/
                 sum(fullSS)*100),3)
})
varexpNEXTflex <-do.call(rbind, lapply(varCompAnalysis, data.frame))
###############
yGene <-as.matrix(Error$Deduped)

varCompAnalysis = apply(t(yGene),1,function(y) {
  if(runif(1) < 1e-4) cat(".")
  fit = lm(y ~ GC + length +FoldG + First_base + Last_base+ First_2_bases + First_4_bases + Last_2_bases + Last_4_bases +rep + duplets+ GGGG+ TTTT + CCCC + AAAA +anyA +anyC + anyG+anyT+avg_Express$Deduped , data=Deduped_pd)
  fit = lm(yGene ~avg_Express$Deduped+ GC+  + length +FoldG  +First_2_bases + Last_2_bases+ anyA + anyT + anyC + duplets + GGGG + TTTT + CCCC +AAAA , data=Deduped_pd, singular.ok = TRUE)
  full =Anova(fit, type = "II")
  fullSS =full$"Sum Sq"
  signif(cbind(full,PctExp=fullSS/
                 sum(fullSS)*100),3)
})

varexpDeduped <-do.call(rbind, lapply(varCompAnalysis, data.frame))

###############
yGene <-as.matrix(Error$Fivepercent)

varCompAnalysis = apply(t(yGene),1,function(y) {
  if(runif(1) < 1e-4) cat(".")
  #fit = lm(y ~ GC+  + length +FoldG + First_base + Last_base+ First_2_bases + First_4_bases + Last_2_bases + Last_4_bases +rep + duplets+ GGGG+ TTTT + CCCC + AAAA +anyA +anyC + anyG + anyT +avg_Express$Fivepercent , data=Fivepercent_pd, singular.ok = TRUE)
  fit = lm(yGene ~avg_Express$Fivepercent+ GC+  + length +FoldG  +First_2_bases + Last_2_bases+ anyA + anyT + anyC + duplets + GGGG + TTTT + CCCC +AAAA , data=Fivepercent_pd, singular.ok = TRUE)
  full =Anova(fit, type = "II")
  fullSS =full$"Sum Sq"
  signif(cbind(full,PctExp=fullSS/
                 sum(fullSS)*100),3)
})

varexpFivepercent<-do.call(rbind, lapply(varCompAnalysis, data.frame))


### a different method - gives similar results
require(variancePartition)
form <- ~avg_Express$Fivepercent+ GC+  + length +FoldG  +First_base + Last_base+ anyA + anyT + anyC + duplets + GGGG + TTTT + CCCC +AAAA
varPart <- fitVarPartModel(t(yGene), form, as.data.frame(Fivepercent_pd), showWarnings = FALSE)
varGene = extractVarPart(varPart, showWarnings = FALSE)
apply(varGene, 2, mean)

#put together
varCompAnalysis <-list(varexpclontech, varexpIllumina, varexpNEB, varexpNEXTflex, varexpDeduped, varexpFivepercent)
names(varCompAnalysis) <- c("Clontech","Illumina","NEB","NEXTflex","Deduped", "Fivepercent")
varexp2 <-do.call(cbind, lapply(varCompAnalysis, data.frame))
varexp_PctExp<-varexp2[grep("PctExp", colnames(varexp2))]
colnames(varexp_PctExp) <- c("Clontech","Illumina","NEB","NEXTflex","Deduped", "Fivepercent")
#varexp_PctExp<- varexp_PctExp[-grep("(Intercept)",rownames(varexp_PctExp)),]
rownames(varexp_PctExp)[1] <- "Expression"

```


```{r, eval=FALSE}
library(pheatmap)


varexp_PctExp3<- varexp_PctExp[-grep("Residual",rownames(varexp_PctExp)),]
varexp_PctExp3$Fake <- c(70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
pdf(file =here("Figures/Raw_plots/Fig.5.b.pdf"),width=3,height=7, onefile = FALSE)
pheatmap(varexp_PctExp3, main = "Percent of batch error variance explained", cluster_cols = FALSE, cluster_rows = FALSE)
dev.off()

####weighted by overall variance by multiplying by kit variance and dividing by mean of all kit variance
varexp_PctExp2<-varexp_PctExp
varexp_PctExp2<-((varexp_PctExp2*variance)/mean(unlist(variance)))
varexp_PctExp2<- varexp_PctExp2[-grep("Residuals",rownames(varexp_PctExp2)),]
pdf(file =here("Figures/Raw_plots/Fig.5.c.pdf"),width=3,height=7, onefile = FALSE)
pheatmap(varexp_PctExp2, cluster_cols = FALSE, main = "Percent of batch error variance explained \n weighted by overall varaince for each kit", cluster_rows = FALSE)
dev.off()
```

Expression plot
```{r}
#avg_Express - this is the log2 expression
#Error
library(ggpubr)
Clontech_exp <-data.frame(Error =Error$Clontech, Expression =avg_Express$Clontech, Kit = rep("Clontech",162))
Illumina_exp <-data.frame(Error =Error$Illumina, Expression =avg_Express$Illumina, Kit = rep("Illumina",162))
NEB_exp <-data.frame(Error =Error$NEB, Expression =avg_Express$NEB, Kit = rep("NEB",162))
NEXTflex_exp <-data.frame(Error =Error$NEXTflex, Expression =avg_Express$NEXTflex, Kit = rep("NEXTflex",162))
Deduped_exp <-data.frame(Error =Error$Deduped, Expression =avg_Express$Deduped, Kit = rep("Deduped",162))
Fivepercent_exp <-data.frame(Error =Error$Fivepercent, Expression =avg_Express$Fivepercent, Kit = rep("Fivepercent",162))

exp_error <- rbind(Clontech_exp, Illumina_exp, NEB_exp, NEXTflex_exp, Deduped_exp, Fivepercent_exp)

pdf(file =here("Figures/Raw_plots/Fig.5.d.pdf"),width=10,height=4, onefile=FALSE)
ggplot(exp_error, aes(x = Expression, y = Error, col = Kit)) + geom_point()+ stat_smooth(method = "loess")+ facet_grid(.~Kit) + theme(legend.position = "none", axis.text.x = element_text(size =17, angle = 60, hjust = 1), axis.text.y = element_text(size =15, hjust = 1), axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 20)) + labs( x= "Expression", y = " Error across Batch", title = " Relationship of Error and Expression") + stat_cor(method = "pearson",  label.x = 10, label.y = 15, size =4.5, col = "black", label.sep = "\n")
dev.off()

summary(lm(Clontech_exp$Error ~ Clontech_exp$Expression))
summary(lm(Illumina_exp$Error ~ Illumina_exp$Expression))
summary(lm(NEB_exp$Error ~ NEB_exp$Expression))
summary(lm(NEXTflex_exp$Error ~ NEXTflex_exp$Expression))
summary(lm(Deduped_exp$Error ~ Deduped_exp$Expression))
summary(lm(Fivepercent_exp$Error ~ Fivepercent_exp$Expression))
cor.test(y =Clontech_exp$Error, x =Clontech_exp$Expression)
cor.test(y =Illumina_exp$Error,x =Illumina_exp$Expression)
cor.test(y =NEB_exp$Error,x =NEB_exp$Expression)
cor.test(y =NEXTflex_exp$Error,x =NEXTflex_exp$Expression)
cor.test(y =Deduped_exp$Error, x =Deduped_exp$Expression)
cor.test(y =Fivepercent_exp$Error, x =Fivepercent_exp$Expression)
```

#GC content
```{r}
Clontech_exp <-data.frame(Error =Error$Clontech, Expression =pd$GC, Kit = rep("Clontech",162))
Illumina_exp <-data.frame(Error =Error$Illumina, Expression =pd$GC, Kit = rep("Illumina",162))
NEB_exp <-data.frame(Error =Error$NEB, Expression =pd$GC, Kit = rep("NEB",162))
NEXTflex_exp <-data.frame(Error =Error$NEXTflex, Expression =pd$GC, Kit = rep("NEXTflex",162))
Deduped_exp <-data.frame(Error =Error$Deduped, Expression =pd$GC, Kit = rep("Deduped",162))
Fivepercent_exp <-data.frame(Error =Error$Fivepercent, Expression =pd$GC, Kit = rep("Fivepercent",162))

exp_error <- rbind(Clontech_exp, Illumina_exp, NEB_exp, NEXTflex_exp, Deduped_exp, Fivepercent_exp)

ggplot(exp_error, aes(x = Expression, y = Error, col = Kit)) + geom_point()+ stat_smooth(method = "loess")+ facet_grid(.~Kit, scales="free") + theme(legend.position = "none", axis.text.x = element_text(size =17, angle = 60, hjust = 1), axis.text.y = element_text(size =15, hjust = 1), axis.title=element_text(size = 20), plot.title = element_text(size = 30), strip.text.x = element_text(size = 20)) + labs( x= "GC Content", y = " Error across Batch", title = " Relationship of GC Content and Error") 
```




#First 2 bases
```{r}
library(pheatmap)
errorFirst<-data.frame(First_2_bases =pd$First_2_bases, Error)
aggdata <-aggregate(errorFirst[-1], by=list(errorFirst$First_2_bases), FUN=mean)
rownames(aggdata) <- aggdata$Group.1
aggdata<-aggdata[which(colnames(aggdata)!="Group.1")]

pheatmap(aggdata,cluster_cols = FALSE, main = "Batch error of sequences with different first bases")
pheatmap(aggdata,cluster_cols = FALSE,cluster_rows = FALSE, main = "Batch error of sequences with different first bases")


errorLast<-data.frame(Last_2_bases =pd$Last_2_bases, Error)
aggdata <-aggregate(errorLast[-1], by=list(errorLast$Last_2_bases), FUN=mean)
rownames(aggdata) <- aggdata$Group.1
aggdata<-aggdata[which(colnames(aggdata)!="Group.1")]

pheatmap(aggdata,cluster_cols = FALSE, main = "Batch error of sequences with different last bases")
pheatmap(aggdata,cluster_cols = FALSE,cluster_rows = FALSE, main = "Batch error of sequences with different last bases")
```






#### methods triplicate consistency
```{r}

library(ffpe)
ranks_error<-data.frame(sapply(-Error, rank))#ranked so 1 is the highest error
rownames(ranks_error)<-rownames(Error)
# ranks_error <-(ranks_error[grep("Clontech", colnames(ranks_error))])
# ranks_error <-(ranks_error[grep("Illumina", colnames(ranks_error))])
# ranks_error <-(ranks_error[grep("NEB", colnames(ranks_error))])
# ranks_error <-(ranks_error[grep("NEXTflex", colnames(ranks_error))])
# ranks_error <-(ranks_error[grep("Deduped", colnames(ranks_error))])
# ranks_error <-(ranks_error[grep("Fivepercent", colnames(ranks_error))])
# ranked_miRNA<-list()

library(RColorBrewer)
trop = cols <- brewer.pal(9, "Set1")
#1000ng -rel to Clontech
forcatplot_1000 <- list(ranks_error$Clontech, ranks_error$Illumina, ranks_error$NEB, ranks_error$NEXTflex, ranks_error$Deduped, ranks_error$Fivepercent)
test <-c(rep(0,162))
forcatplot_1000[[7]] <- c(rep(0,162))
catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(forcatplot_1000[[i]],forcatplot_1000[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Batch_error_Clontech.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to Clontech",xlab="Rank", xlim=c(1,162), cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(100,0.5,legend=c("Clontech_vs_Illumina","Clontech_vs_NEB", "Clontech_vs_NEXTflex","Clontech_vs_Deduped","Clontech_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)
dev.off()

#1000ng -rel to NEXTflex
forcatplot_1000 <- list( ranks_error$NEXTflex,ranks_error$Illumina, ranks_error$NEB, ranks_error$Clontech, ranks_error$Deduped, ranks_error$Fivepercent)
forcatplot_1000[[7]] <- c(rep(0,162))
catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(forcatplot_1000[[i]],forcatplot_1000[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Batch_error_NEXTflex.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to NEXTflex",xlab="Rank", xlim=c(1,162), cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(100,0.5,legend=c("NEXTflex_vs_Illumina","NEXTflex_vs_NEB", "NEXTflex_vs_Clontech","NEXTflex_vs_Deduped","NEXTflex_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)
dev.off()

#1000ng -rel to Illumina
forcatplot_1000 <- list(ranks_error$Illumina,ranks_error$Clontech,ranks_error$NEB, ranks_error$NEXTflex, ranks_error$Deduped, ranks_error$Fivepercent)
forcatplot_1000[[7]] <- c(rep(0,162))
catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(forcatplot_1000[[i]],forcatplot_1000[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Batch_error_Illumina.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to Illumina",xlab="Rank", xlim=c(1,162), cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(100,0.5,legend=c("Illumina_vs_Clontech","Illumina_vs_NEB", "Illumina_vs_NEXTflex","Illumina_vs_Deduped","Illumina_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)
dev.off()

#1000ng -rel to NEB
forcatplot_1000 <- list(ranks_error$NEB,ranks_error$Clontech,ranks_error$Illumina, ranks_error$NEXTflex, ranks_error$Deduped, ranks_error$Fivepercent)
forcatplot_1000[[7]] <- c(rep(0,162))
catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(forcatplot_1000[[i]],forcatplot_1000[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Batch_error_NEB.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to NEB",xlab="Rank", xlim=c(1,162), cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(100,0.5,legend=c("NEB_vs_Clontech","NEB_vs_Illumina", "NEB_vs_NEXTflex","NEB_vs_Deduped","NEB_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)
dev.off()

#1000ng -rel to Deduped
forcatplot_1000 <- list(ranks_error$Deduped,ranks_error$Clontech,ranks_error$Illumina, ranks_error$NEB, ranks_error$NEXTflex, ranks_error$Fivepercent)
forcatplot_1000[[7]] <- c(rep(0,162))
catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(forcatplot_1000[[i]],forcatplot_1000[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Batch_error_Deduped.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to Deduped",xlab="Rank", xlim=c(1,162), cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(100,0.5,legend=c("Deduped_vs_Clontech","Deduped_vs_Illumina","Deduped_vs_NEB", "Deduped_vs_NEXTflex","Deduped_vs_Fivepercent", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)

dev.off()


#1000ng -rel to Fivepercent
forcatplot_1000 <- list(ranks_error$Fivepercent,ranks_error$Clontech,ranks_error$Illumina, ranks_error$NEB, ranks_error$NEXTflex, ranks_error$Deduped)
forcatplot_1000[[7]] <- c(rep(0,162))
catplots <-list()
for(i in 1:7){
  catplots[[i]] = CATplot(forcatplot_1000[[i]],forcatplot_1000[[1]],make.plot=F)
}
pdf(file =here("Supplement/Figures/Batch_error_Fivepercent.pdf"),width=10,height=8, onefile=FALSE)
par(mar=c(5,5,5,5))
plot(catplots[[2]],ylim=c(0,1),col=trop[1],lwd=3,type="l",ylab="Concordance Between Methods relative to Fivepercent",xlab="Rank", xlim=c(1,162), cex.lab=1.8, cex.axis=2)
lines(catplots[[3]],col=trop[2],lwd=3,lty=2)
lines(catplots[[4]],col=trop[3],lwd=3)
lines(catplots[[5]],col=trop[4],lwd=3,lty=3)
lines(catplots[[6]],col=trop[5],lwd=3,lty=1)
lines(catplots[[1]],col=trop[7],lwd=3,lty=3)
lines(catplots[[7]], col=trop[9],lwd=3)
legend(100,0.5,legend=c("Fivepercent_vs_Clontech","Fivepercent_vs_Illumina","Fivepercent_vs_NEB", "Fivepercent_vs_NEXTflex","Fivepercent_vs_Deduped", "Perfect_concordance", "No_concordance"),col=trop[c(1,2,3,4,5,7,9)],lty=c(1,2,1,3,1,3,1),lwd=3, cex = 1.2)

dev.off()


```

